// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbft.proto

package com.gbft.framework.data;

public interface ConfigDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ConfigData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; data = 1;</code>
   */
  int getDataCount();
  /**
   * <code>map&lt;string, string&gt; data = 1;</code>
   */
  boolean containsData(
      java.lang.String key);
  /**
   * Use {@link #getDataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getData();
  /**
   * <code>map&lt;string, string&gt; data = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getDataMap();
  /**
   * <code>map&lt;string, string&gt; data = 1;</code>
   */

  java.lang.String getDataOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; data = 1;</code>
   */

  java.lang.String getDataOrThrow(
      java.lang.String key);

  /**
   * <code>string defaultProtocol = 2;</code>
   * @return The defaultProtocol.
   */
  java.lang.String getDefaultProtocol();
  /**
   * <code>string defaultProtocol = 2;</code>
   * @return The bytes for defaultProtocol.
   */
  com.google.protobuf.ByteString
      getDefaultProtocolBytes();

  /**
   * <code>repeated .UnitData units = 3;</code>
   */
  java.util.List<com.gbft.framework.data.UnitData> 
      getUnitsList();
  /**
   * <code>repeated .UnitData units = 3;</code>
   */
  com.gbft.framework.data.UnitData getUnits(int index);
  /**
   * <code>repeated .UnitData units = 3;</code>
   */
  int getUnitsCount();
  /**
   * <code>repeated .UnitData units = 3;</code>
   */
  java.util.List<? extends com.gbft.framework.data.UnitDataOrBuilder> 
      getUnitsOrBuilderList();
  /**
   * <code>repeated .UnitData units = 3;</code>
   */
  com.gbft.framework.data.UnitDataOrBuilder getUnitsOrBuilder(
      int index);
}
