// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbft.proto

package com.gbft.framework.data;

/**
 * Protobuf type {@code ConfigData}
 */
public final class ConfigData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ConfigData)
    ConfigDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConfigData.newBuilder() to construct.
  private ConfigData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConfigData() {
    defaultProtocol_ = "";
    units_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ConfigData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ConfigData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              data_ = com.google.protobuf.MapField.newMapField(
                  DataDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            data__ = input.readMessage(
                DataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            data_.getMutableMap().put(
                data__.getKey(), data__.getValue());
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            defaultProtocol_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              units_ = new java.util.ArrayList<com.gbft.framework.data.UnitData>();
              mutable_bitField0_ |= 0x00000002;
            }
            units_.add(
                input.readMessage(com.gbft.framework.data.UnitData.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        units_ = java.util.Collections.unmodifiableList(units_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gbft.framework.data.Gbft.internal_static_ConfigData_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetData();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gbft.framework.data.Gbft.internal_static_ConfigData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gbft.framework.data.ConfigData.class, com.gbft.framework.data.ConfigData.Builder.class);
  }

  public static final int DATA_FIELD_NUMBER = 1;
  private static final class DataDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.gbft.framework.data.Gbft.internal_static_ConfigData_DataEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> data_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetData() {
    if (data_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          DataDefaultEntryHolder.defaultEntry);
    }
    return data_;
  }

  public int getDataCount() {
    return internalGetData().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; data = 1;</code>
   */

  @java.lang.Override
  public boolean containsData(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetData().getMap().containsKey(key);
  }
  /**
   * Use {@link #getDataMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getData() {
    return getDataMap();
  }
  /**
   * <code>map&lt;string, string&gt; data = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getDataMap() {
    return internalGetData().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; data = 1;</code>
   */
  @java.lang.Override

  public java.lang.String getDataOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetData().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; data = 1;</code>
   */
  @java.lang.Override

  public java.lang.String getDataOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetData().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int DEFAULTPROTOCOL_FIELD_NUMBER = 2;
  private volatile java.lang.Object defaultProtocol_;
  /**
   * <code>string defaultProtocol = 2;</code>
   * @return The defaultProtocol.
   */
  @java.lang.Override
  public java.lang.String getDefaultProtocol() {
    java.lang.Object ref = defaultProtocol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      defaultProtocol_ = s;
      return s;
    }
  }
  /**
   * <code>string defaultProtocol = 2;</code>
   * @return The bytes for defaultProtocol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDefaultProtocolBytes() {
    java.lang.Object ref = defaultProtocol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      defaultProtocol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UNITS_FIELD_NUMBER = 3;
  private java.util.List<com.gbft.framework.data.UnitData> units_;
  /**
   * <code>repeated .UnitData units = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.gbft.framework.data.UnitData> getUnitsList() {
    return units_;
  }
  /**
   * <code>repeated .UnitData units = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.gbft.framework.data.UnitDataOrBuilder> 
      getUnitsOrBuilderList() {
    return units_;
  }
  /**
   * <code>repeated .UnitData units = 3;</code>
   */
  @java.lang.Override
  public int getUnitsCount() {
    return units_.size();
  }
  /**
   * <code>repeated .UnitData units = 3;</code>
   */
  @java.lang.Override
  public com.gbft.framework.data.UnitData getUnits(int index) {
    return units_.get(index);
  }
  /**
   * <code>repeated .UnitData units = 3;</code>
   */
  @java.lang.Override
  public com.gbft.framework.data.UnitDataOrBuilder getUnitsOrBuilder(
      int index) {
    return units_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetData(),
        DataDefaultEntryHolder.defaultEntry,
        1);
    if (!getDefaultProtocolBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, defaultProtocol_);
    }
    for (int i = 0; i < units_.size(); i++) {
      output.writeMessage(3, units_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetData().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      data__ = DataDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, data__);
    }
    if (!getDefaultProtocolBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, defaultProtocol_);
    }
    for (int i = 0; i < units_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, units_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gbft.framework.data.ConfigData)) {
      return super.equals(obj);
    }
    com.gbft.framework.data.ConfigData other = (com.gbft.framework.data.ConfigData) obj;

    if (!internalGetData().equals(
        other.internalGetData())) return false;
    if (!getDefaultProtocol()
        .equals(other.getDefaultProtocol())) return false;
    if (!getUnitsList()
        .equals(other.getUnitsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetData().getMap().isEmpty()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + internalGetData().hashCode();
    }
    hash = (37 * hash) + DEFAULTPROTOCOL_FIELD_NUMBER;
    hash = (53 * hash) + getDefaultProtocol().hashCode();
    if (getUnitsCount() > 0) {
      hash = (37 * hash) + UNITS_FIELD_NUMBER;
      hash = (53 * hash) + getUnitsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gbft.framework.data.ConfigData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.ConfigData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.ConfigData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.ConfigData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.ConfigData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.ConfigData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.ConfigData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.ConfigData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gbft.framework.data.ConfigData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.ConfigData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gbft.framework.data.ConfigData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.ConfigData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gbft.framework.data.ConfigData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ConfigData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ConfigData)
      com.gbft.framework.data.ConfigDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gbft.framework.data.Gbft.internal_static_ConfigData_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gbft.framework.data.Gbft.internal_static_ConfigData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gbft.framework.data.ConfigData.class, com.gbft.framework.data.ConfigData.Builder.class);
    }

    // Construct using com.gbft.framework.data.ConfigData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUnitsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableData().clear();
      defaultProtocol_ = "";

      if (unitsBuilder_ == null) {
        units_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        unitsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gbft.framework.data.Gbft.internal_static_ConfigData_descriptor;
    }

    @java.lang.Override
    public com.gbft.framework.data.ConfigData getDefaultInstanceForType() {
      return com.gbft.framework.data.ConfigData.getDefaultInstance();
    }

    @java.lang.Override
    public com.gbft.framework.data.ConfigData build() {
      com.gbft.framework.data.ConfigData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gbft.framework.data.ConfigData buildPartial() {
      com.gbft.framework.data.ConfigData result = new com.gbft.framework.data.ConfigData(this);
      int from_bitField0_ = bitField0_;
      result.data_ = internalGetData();
      result.data_.makeImmutable();
      result.defaultProtocol_ = defaultProtocol_;
      if (unitsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          units_ = java.util.Collections.unmodifiableList(units_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.units_ = units_;
      } else {
        result.units_ = unitsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gbft.framework.data.ConfigData) {
        return mergeFrom((com.gbft.framework.data.ConfigData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gbft.framework.data.ConfigData other) {
      if (other == com.gbft.framework.data.ConfigData.getDefaultInstance()) return this;
      internalGetMutableData().mergeFrom(
          other.internalGetData());
      if (!other.getDefaultProtocol().isEmpty()) {
        defaultProtocol_ = other.defaultProtocol_;
        onChanged();
      }
      if (unitsBuilder_ == null) {
        if (!other.units_.isEmpty()) {
          if (units_.isEmpty()) {
            units_ = other.units_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureUnitsIsMutable();
            units_.addAll(other.units_);
          }
          onChanged();
        }
      } else {
        if (!other.units_.isEmpty()) {
          if (unitsBuilder_.isEmpty()) {
            unitsBuilder_.dispose();
            unitsBuilder_ = null;
            units_ = other.units_;
            bitField0_ = (bitField0_ & ~0x00000002);
            unitsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUnitsFieldBuilder() : null;
          } else {
            unitsBuilder_.addAllMessages(other.units_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gbft.framework.data.ConfigData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gbft.framework.data.ConfigData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> data_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetData() {
      if (data_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DataDefaultEntryHolder.defaultEntry);
      }
      return data_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableData() {
      onChanged();;
      if (data_ == null) {
        data_ = com.google.protobuf.MapField.newMapField(
            DataDefaultEntryHolder.defaultEntry);
      }
      if (!data_.isMutable()) {
        data_ = data_.copy();
      }
      return data_;
    }

    public int getDataCount() {
      return internalGetData().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; data = 1;</code>
     */

    @java.lang.Override
    public boolean containsData(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getDataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getData() {
      return getDataMap();
    }
    /**
     * <code>map&lt;string, string&gt; data = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getDataMap() {
      return internalGetData().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; data = 1;</code>
     */
    @java.lang.Override

    public java.lang.String getDataOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; data = 1;</code>
     */
    @java.lang.Override

    public java.lang.String getDataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearData() {
      internalGetMutableData().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; data = 1;</code>
     */

    public Builder removeData(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableData().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableData() {
      return internalGetMutableData().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; data = 1;</code>
     */
    public Builder putData(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableData().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; data = 1;</code>
     */

    public Builder putAllData(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableData().getMutableMap()
          .putAll(values);
      return this;
    }

    private java.lang.Object defaultProtocol_ = "";
    /**
     * <code>string defaultProtocol = 2;</code>
     * @return The defaultProtocol.
     */
    public java.lang.String getDefaultProtocol() {
      java.lang.Object ref = defaultProtocol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        defaultProtocol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string defaultProtocol = 2;</code>
     * @return The bytes for defaultProtocol.
     */
    public com.google.protobuf.ByteString
        getDefaultProtocolBytes() {
      java.lang.Object ref = defaultProtocol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        defaultProtocol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string defaultProtocol = 2;</code>
     * @param value The defaultProtocol to set.
     * @return This builder for chaining.
     */
    public Builder setDefaultProtocol(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      defaultProtocol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string defaultProtocol = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDefaultProtocol() {
      
      defaultProtocol_ = getDefaultInstance().getDefaultProtocol();
      onChanged();
      return this;
    }
    /**
     * <code>string defaultProtocol = 2;</code>
     * @param value The bytes for defaultProtocol to set.
     * @return This builder for chaining.
     */
    public Builder setDefaultProtocolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      defaultProtocol_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.gbft.framework.data.UnitData> units_ =
      java.util.Collections.emptyList();
    private void ensureUnitsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        units_ = new java.util.ArrayList<com.gbft.framework.data.UnitData>(units_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.gbft.framework.data.UnitData, com.gbft.framework.data.UnitData.Builder, com.gbft.framework.data.UnitDataOrBuilder> unitsBuilder_;

    /**
     * <code>repeated .UnitData units = 3;</code>
     */
    public java.util.List<com.gbft.framework.data.UnitData> getUnitsList() {
      if (unitsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(units_);
      } else {
        return unitsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .UnitData units = 3;</code>
     */
    public int getUnitsCount() {
      if (unitsBuilder_ == null) {
        return units_.size();
      } else {
        return unitsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .UnitData units = 3;</code>
     */
    public com.gbft.framework.data.UnitData getUnits(int index) {
      if (unitsBuilder_ == null) {
        return units_.get(index);
      } else {
        return unitsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .UnitData units = 3;</code>
     */
    public Builder setUnits(
        int index, com.gbft.framework.data.UnitData value) {
      if (unitsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUnitsIsMutable();
        units_.set(index, value);
        onChanged();
      } else {
        unitsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .UnitData units = 3;</code>
     */
    public Builder setUnits(
        int index, com.gbft.framework.data.UnitData.Builder builderForValue) {
      if (unitsBuilder_ == null) {
        ensureUnitsIsMutable();
        units_.set(index, builderForValue.build());
        onChanged();
      } else {
        unitsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UnitData units = 3;</code>
     */
    public Builder addUnits(com.gbft.framework.data.UnitData value) {
      if (unitsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUnitsIsMutable();
        units_.add(value);
        onChanged();
      } else {
        unitsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .UnitData units = 3;</code>
     */
    public Builder addUnits(
        int index, com.gbft.framework.data.UnitData value) {
      if (unitsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUnitsIsMutable();
        units_.add(index, value);
        onChanged();
      } else {
        unitsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .UnitData units = 3;</code>
     */
    public Builder addUnits(
        com.gbft.framework.data.UnitData.Builder builderForValue) {
      if (unitsBuilder_ == null) {
        ensureUnitsIsMutable();
        units_.add(builderForValue.build());
        onChanged();
      } else {
        unitsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UnitData units = 3;</code>
     */
    public Builder addUnits(
        int index, com.gbft.framework.data.UnitData.Builder builderForValue) {
      if (unitsBuilder_ == null) {
        ensureUnitsIsMutable();
        units_.add(index, builderForValue.build());
        onChanged();
      } else {
        unitsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UnitData units = 3;</code>
     */
    public Builder addAllUnits(
        java.lang.Iterable<? extends com.gbft.framework.data.UnitData> values) {
      if (unitsBuilder_ == null) {
        ensureUnitsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, units_);
        onChanged();
      } else {
        unitsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .UnitData units = 3;</code>
     */
    public Builder clearUnits() {
      if (unitsBuilder_ == null) {
        units_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        unitsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .UnitData units = 3;</code>
     */
    public Builder removeUnits(int index) {
      if (unitsBuilder_ == null) {
        ensureUnitsIsMutable();
        units_.remove(index);
        onChanged();
      } else {
        unitsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .UnitData units = 3;</code>
     */
    public com.gbft.framework.data.UnitData.Builder getUnitsBuilder(
        int index) {
      return getUnitsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .UnitData units = 3;</code>
     */
    public com.gbft.framework.data.UnitDataOrBuilder getUnitsOrBuilder(
        int index) {
      if (unitsBuilder_ == null) {
        return units_.get(index);  } else {
        return unitsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .UnitData units = 3;</code>
     */
    public java.util.List<? extends com.gbft.framework.data.UnitDataOrBuilder> 
         getUnitsOrBuilderList() {
      if (unitsBuilder_ != null) {
        return unitsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(units_);
      }
    }
    /**
     * <code>repeated .UnitData units = 3;</code>
     */
    public com.gbft.framework.data.UnitData.Builder addUnitsBuilder() {
      return getUnitsFieldBuilder().addBuilder(
          com.gbft.framework.data.UnitData.getDefaultInstance());
    }
    /**
     * <code>repeated .UnitData units = 3;</code>
     */
    public com.gbft.framework.data.UnitData.Builder addUnitsBuilder(
        int index) {
      return getUnitsFieldBuilder().addBuilder(
          index, com.gbft.framework.data.UnitData.getDefaultInstance());
    }
    /**
     * <code>repeated .UnitData units = 3;</code>
     */
    public java.util.List<com.gbft.framework.data.UnitData.Builder> 
         getUnitsBuilderList() {
      return getUnitsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.gbft.framework.data.UnitData, com.gbft.framework.data.UnitData.Builder, com.gbft.framework.data.UnitDataOrBuilder> 
        getUnitsFieldBuilder() {
      if (unitsBuilder_ == null) {
        unitsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.gbft.framework.data.UnitData, com.gbft.framework.data.UnitData.Builder, com.gbft.framework.data.UnitDataOrBuilder>(
                units_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        units_ = null;
      }
      return unitsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ConfigData)
  }

  // @@protoc_insertion_point(class_scope:ConfigData)
  private static final com.gbft.framework.data.ConfigData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gbft.framework.data.ConfigData();
  }

  public static com.gbft.framework.data.ConfigData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConfigData>
      PARSER = new com.google.protobuf.AbstractParser<ConfigData>() {
    @java.lang.Override
    public ConfigData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ConfigData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ConfigData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConfigData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gbft.framework.data.ConfigData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

