// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbft.proto

package com.gbft.framework.data;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Event.EventType event_type = 1;</code>
   * @return The enum numeric value on the wire for eventType.
   */
  int getEventTypeValue();
  /**
   * <code>.Event.EventType event_type = 1;</code>
   * @return The eventType.
   */
  com.gbft.framework.data.Event.EventType getEventType();

  /**
   * <code>.UnitData unit_data = 2;</code>
   * @return Whether the unitData field is set.
   */
  boolean hasUnitData();
  /**
   * <code>.UnitData unit_data = 2;</code>
   * @return The unitData.
   */
  com.gbft.framework.data.UnitData getUnitData();
  /**
   * <code>.UnitData unit_data = 2;</code>
   */
  com.gbft.framework.data.UnitDataOrBuilder getUnitDataOrBuilder();

  /**
   * <code>.ConfigData config_data = 3;</code>
   * @return Whether the configData field is set.
   */
  boolean hasConfigData();
  /**
   * <code>.ConfigData config_data = 3;</code>
   * @return The configData.
   */
  com.gbft.framework.data.ConfigData getConfigData();
  /**
   * <code>.ConfigData config_data = 3;</code>
   */
  com.gbft.framework.data.ConfigDataOrBuilder getConfigDataOrBuilder();

  /**
   * <code>.PluginData plugin_data = 4;</code>
   * @return Whether the pluginData field is set.
   */
  boolean hasPluginData();
  /**
   * <code>.PluginData plugin_data = 4;</code>
   * @return The pluginData.
   */
  com.gbft.framework.data.PluginData getPluginData();
  /**
   * <code>.PluginData plugin_data = 4;</code>
   */
  com.gbft.framework.data.PluginDataOrBuilder getPluginDataOrBuilder();

  /**
   * <code>.ReportData report_data = 5;</code>
   * @return Whether the reportData field is set.
   */
  boolean hasReportData();
  /**
   * <code>.ReportData report_data = 5;</code>
   * @return The reportData.
   */
  com.gbft.framework.data.ReportData getReportData();
  /**
   * <code>.ReportData report_data = 5;</code>
   */
  com.gbft.framework.data.ReportDataOrBuilder getReportDataOrBuilder();

  /**
   * <code>.MessageBlock message_block = 6;</code>
   * @return Whether the messageBlock field is set.
   */
  boolean hasMessageBlock();
  /**
   * <code>.MessageBlock message_block = 6;</code>
   * @return The messageBlock.
   */
  com.gbft.framework.data.MessageBlock getMessageBlock();
  /**
   * <code>.MessageBlock message_block = 6;</code>
   */
  com.gbft.framework.data.MessageBlockOrBuilder getMessageBlockOrBuilder();

  /**
   * <code>int32 target = 7;</code>
   * @return The target.
   */
  int getTarget();

  public com.gbft.framework.data.Event.EventDataCase getEventDataCase();
}
