// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbft.proto

package com.gbft.framework.data;

/**
 * Protobuf type {@code Event}
 */
public final class Event extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Event)
    EventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Event.newBuilder() to construct.
  private Event(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Event() {
    eventType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Event();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Event(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            eventType_ = rawValue;
            break;
          }
          case 18: {
            com.gbft.framework.data.UnitData.Builder subBuilder = null;
            if (eventDataCase_ == 2) {
              subBuilder = ((com.gbft.framework.data.UnitData) eventData_).toBuilder();
            }
            eventData_ =
                input.readMessage(com.gbft.framework.data.UnitData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.gbft.framework.data.UnitData) eventData_);
              eventData_ = subBuilder.buildPartial();
            }
            eventDataCase_ = 2;
            break;
          }
          case 26: {
            com.gbft.framework.data.ConfigData.Builder subBuilder = null;
            if (eventDataCase_ == 3) {
              subBuilder = ((com.gbft.framework.data.ConfigData) eventData_).toBuilder();
            }
            eventData_ =
                input.readMessage(com.gbft.framework.data.ConfigData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.gbft.framework.data.ConfigData) eventData_);
              eventData_ = subBuilder.buildPartial();
            }
            eventDataCase_ = 3;
            break;
          }
          case 34: {
            com.gbft.framework.data.PluginData.Builder subBuilder = null;
            if (eventDataCase_ == 4) {
              subBuilder = ((com.gbft.framework.data.PluginData) eventData_).toBuilder();
            }
            eventData_ =
                input.readMessage(com.gbft.framework.data.PluginData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.gbft.framework.data.PluginData) eventData_);
              eventData_ = subBuilder.buildPartial();
            }
            eventDataCase_ = 4;
            break;
          }
          case 42: {
            com.gbft.framework.data.ReportData.Builder subBuilder = null;
            if (eventDataCase_ == 5) {
              subBuilder = ((com.gbft.framework.data.ReportData) eventData_).toBuilder();
            }
            eventData_ =
                input.readMessage(com.gbft.framework.data.ReportData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.gbft.framework.data.ReportData) eventData_);
              eventData_ = subBuilder.buildPartial();
            }
            eventDataCase_ = 5;
            break;
          }
          case 50: {
            com.gbft.framework.data.MessageBlock.Builder subBuilder = null;
            if (eventDataCase_ == 6) {
              subBuilder = ((com.gbft.framework.data.MessageBlock) eventData_).toBuilder();
            }
            eventData_ =
                input.readMessage(com.gbft.framework.data.MessageBlock.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.gbft.framework.data.MessageBlock) eventData_);
              eventData_ = subBuilder.buildPartial();
            }
            eventDataCase_ = 6;
            break;
          }
          case 56: {
            eventDataCase_ = 7;
            eventData_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gbft.framework.data.Gbft.internal_static_Event_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gbft.framework.data.Gbft.internal_static_Event_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gbft.framework.data.Event.class, com.gbft.framework.data.Event.Builder.class);
  }

  /**
   * Protobuf enum {@code Event.EventType}
   */
  public enum EventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>INIT = 0;</code>
     */
    INIT(0),
    /**
     * <code>CONFIG = 1;</code>
     */
    CONFIG(1),
    /**
     * <code>READY = 2;</code>
     */
    READY(2),
    /**
     * <code>PLUGIN_INIT = 3;</code>
     */
    PLUGIN_INIT(3),
    /**
     * <code>START = 4;</code>
     */
    START(4),
    /**
     * <code>BLOCK = 5;</code>
     */
    BLOCK(5),
    /**
     * <code>STOP = 6;</code>
     */
    STOP(6),
    /**
     * <code>EXIT = 7;</code>
     */
    EXIT(7),
    /**
     * <code>BENCHMARK_START = 8;</code>
     */
    BENCHMARK_START(8),
    /**
     * <code>BENCHMARK_REPORT = 9;</code>
     */
    BENCHMARK_REPORT(9),
    /**
     * <code>MESSAGE = 10;</code>
     */
    MESSAGE(10),
    /**
     * <code>CONNECTION = 11;</code>
     */
    CONNECTION(11),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>INIT = 0;</code>
     */
    public static final int INIT_VALUE = 0;
    /**
     * <code>CONFIG = 1;</code>
     */
    public static final int CONFIG_VALUE = 1;
    /**
     * <code>READY = 2;</code>
     */
    public static final int READY_VALUE = 2;
    /**
     * <code>PLUGIN_INIT = 3;</code>
     */
    public static final int PLUGIN_INIT_VALUE = 3;
    /**
     * <code>START = 4;</code>
     */
    public static final int START_VALUE = 4;
    /**
     * <code>BLOCK = 5;</code>
     */
    public static final int BLOCK_VALUE = 5;
    /**
     * <code>STOP = 6;</code>
     */
    public static final int STOP_VALUE = 6;
    /**
     * <code>EXIT = 7;</code>
     */
    public static final int EXIT_VALUE = 7;
    /**
     * <code>BENCHMARK_START = 8;</code>
     */
    public static final int BENCHMARK_START_VALUE = 8;
    /**
     * <code>BENCHMARK_REPORT = 9;</code>
     */
    public static final int BENCHMARK_REPORT_VALUE = 9;
    /**
     * <code>MESSAGE = 10;</code>
     */
    public static final int MESSAGE_VALUE = 10;
    /**
     * <code>CONNECTION = 11;</code>
     */
    public static final int CONNECTION_VALUE = 11;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EventType forNumber(int value) {
      switch (value) {
        case 0: return INIT;
        case 1: return CONFIG;
        case 2: return READY;
        case 3: return PLUGIN_INIT;
        case 4: return START;
        case 5: return BLOCK;
        case 6: return STOP;
        case 7: return EXIT;
        case 8: return BENCHMARK_START;
        case 9: return BENCHMARK_REPORT;
        case 10: return MESSAGE;
        case 11: return CONNECTION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EventType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
            public EventType findValueByNumber(int number) {
              return EventType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.gbft.framework.data.Event.getDescriptor().getEnumTypes().get(0);
    }

    private static final EventType[] VALUES = values();

    public static EventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EventType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Event.EventType)
  }

  private int eventDataCase_ = 0;
  private java.lang.Object eventData_;
  public enum EventDataCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    UNIT_DATA(2),
    CONFIG_DATA(3),
    PLUGIN_DATA(4),
    REPORT_DATA(5),
    MESSAGE_BLOCK(6),
    TARGET(7),
    EVENTDATA_NOT_SET(0);
    private final int value;
    private EventDataCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventDataCase valueOf(int value) {
      return forNumber(value);
    }

    public static EventDataCase forNumber(int value) {
      switch (value) {
        case 2: return UNIT_DATA;
        case 3: return CONFIG_DATA;
        case 4: return PLUGIN_DATA;
        case 5: return REPORT_DATA;
        case 6: return MESSAGE_BLOCK;
        case 7: return TARGET;
        case 0: return EVENTDATA_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public EventDataCase
  getEventDataCase() {
    return EventDataCase.forNumber(
        eventDataCase_);
  }

  public static final int EVENT_TYPE_FIELD_NUMBER = 1;
  private int eventType_;
  /**
   * <code>.Event.EventType event_type = 1;</code>
   * @return The enum numeric value on the wire for eventType.
   */
  @java.lang.Override public int getEventTypeValue() {
    return eventType_;
  }
  /**
   * <code>.Event.EventType event_type = 1;</code>
   * @return The eventType.
   */
  @java.lang.Override public com.gbft.framework.data.Event.EventType getEventType() {
    @SuppressWarnings("deprecation")
    com.gbft.framework.data.Event.EventType result = com.gbft.framework.data.Event.EventType.valueOf(eventType_);
    return result == null ? com.gbft.framework.data.Event.EventType.UNRECOGNIZED : result;
  }

  public static final int UNIT_DATA_FIELD_NUMBER = 2;
  /**
   * <code>.UnitData unit_data = 2;</code>
   * @return Whether the unitData field is set.
   */
  @java.lang.Override
  public boolean hasUnitData() {
    return eventDataCase_ == 2;
  }
  /**
   * <code>.UnitData unit_data = 2;</code>
   * @return The unitData.
   */
  @java.lang.Override
  public com.gbft.framework.data.UnitData getUnitData() {
    if (eventDataCase_ == 2) {
       return (com.gbft.framework.data.UnitData) eventData_;
    }
    return com.gbft.framework.data.UnitData.getDefaultInstance();
  }
  /**
   * <code>.UnitData unit_data = 2;</code>
   */
  @java.lang.Override
  public com.gbft.framework.data.UnitDataOrBuilder getUnitDataOrBuilder() {
    if (eventDataCase_ == 2) {
       return (com.gbft.framework.data.UnitData) eventData_;
    }
    return com.gbft.framework.data.UnitData.getDefaultInstance();
  }

  public static final int CONFIG_DATA_FIELD_NUMBER = 3;
  /**
   * <code>.ConfigData config_data = 3;</code>
   * @return Whether the configData field is set.
   */
  @java.lang.Override
  public boolean hasConfigData() {
    return eventDataCase_ == 3;
  }
  /**
   * <code>.ConfigData config_data = 3;</code>
   * @return The configData.
   */
  @java.lang.Override
  public com.gbft.framework.data.ConfigData getConfigData() {
    if (eventDataCase_ == 3) {
       return (com.gbft.framework.data.ConfigData) eventData_;
    }
    return com.gbft.framework.data.ConfigData.getDefaultInstance();
  }
  /**
   * <code>.ConfigData config_data = 3;</code>
   */
  @java.lang.Override
  public com.gbft.framework.data.ConfigDataOrBuilder getConfigDataOrBuilder() {
    if (eventDataCase_ == 3) {
       return (com.gbft.framework.data.ConfigData) eventData_;
    }
    return com.gbft.framework.data.ConfigData.getDefaultInstance();
  }

  public static final int PLUGIN_DATA_FIELD_NUMBER = 4;
  /**
   * <code>.PluginData plugin_data = 4;</code>
   * @return Whether the pluginData field is set.
   */
  @java.lang.Override
  public boolean hasPluginData() {
    return eventDataCase_ == 4;
  }
  /**
   * <code>.PluginData plugin_data = 4;</code>
   * @return The pluginData.
   */
  @java.lang.Override
  public com.gbft.framework.data.PluginData getPluginData() {
    if (eventDataCase_ == 4) {
       return (com.gbft.framework.data.PluginData) eventData_;
    }
    return com.gbft.framework.data.PluginData.getDefaultInstance();
  }
  /**
   * <code>.PluginData plugin_data = 4;</code>
   */
  @java.lang.Override
  public com.gbft.framework.data.PluginDataOrBuilder getPluginDataOrBuilder() {
    if (eventDataCase_ == 4) {
       return (com.gbft.framework.data.PluginData) eventData_;
    }
    return com.gbft.framework.data.PluginData.getDefaultInstance();
  }

  public static final int REPORT_DATA_FIELD_NUMBER = 5;
  /**
   * <code>.ReportData report_data = 5;</code>
   * @return Whether the reportData field is set.
   */
  @java.lang.Override
  public boolean hasReportData() {
    return eventDataCase_ == 5;
  }
  /**
   * <code>.ReportData report_data = 5;</code>
   * @return The reportData.
   */
  @java.lang.Override
  public com.gbft.framework.data.ReportData getReportData() {
    if (eventDataCase_ == 5) {
       return (com.gbft.framework.data.ReportData) eventData_;
    }
    return com.gbft.framework.data.ReportData.getDefaultInstance();
  }
  /**
   * <code>.ReportData report_data = 5;</code>
   */
  @java.lang.Override
  public com.gbft.framework.data.ReportDataOrBuilder getReportDataOrBuilder() {
    if (eventDataCase_ == 5) {
       return (com.gbft.framework.data.ReportData) eventData_;
    }
    return com.gbft.framework.data.ReportData.getDefaultInstance();
  }

  public static final int MESSAGE_BLOCK_FIELD_NUMBER = 6;
  /**
   * <code>.MessageBlock message_block = 6;</code>
   * @return Whether the messageBlock field is set.
   */
  @java.lang.Override
  public boolean hasMessageBlock() {
    return eventDataCase_ == 6;
  }
  /**
   * <code>.MessageBlock message_block = 6;</code>
   * @return The messageBlock.
   */
  @java.lang.Override
  public com.gbft.framework.data.MessageBlock getMessageBlock() {
    if (eventDataCase_ == 6) {
       return (com.gbft.framework.data.MessageBlock) eventData_;
    }
    return com.gbft.framework.data.MessageBlock.getDefaultInstance();
  }
  /**
   * <code>.MessageBlock message_block = 6;</code>
   */
  @java.lang.Override
  public com.gbft.framework.data.MessageBlockOrBuilder getMessageBlockOrBuilder() {
    if (eventDataCase_ == 6) {
       return (com.gbft.framework.data.MessageBlock) eventData_;
    }
    return com.gbft.framework.data.MessageBlock.getDefaultInstance();
  }

  public static final int TARGET_FIELD_NUMBER = 7;
  /**
   * <code>int32 target = 7;</code>
   * @return The target.
   */
  @java.lang.Override
  public int getTarget() {
    if (eventDataCase_ == 7) {
      return (java.lang.Integer) eventData_;
    }
    return 0;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (eventType_ != com.gbft.framework.data.Event.EventType.INIT.getNumber()) {
      output.writeEnum(1, eventType_);
    }
    if (eventDataCase_ == 2) {
      output.writeMessage(2, (com.gbft.framework.data.UnitData) eventData_);
    }
    if (eventDataCase_ == 3) {
      output.writeMessage(3, (com.gbft.framework.data.ConfigData) eventData_);
    }
    if (eventDataCase_ == 4) {
      output.writeMessage(4, (com.gbft.framework.data.PluginData) eventData_);
    }
    if (eventDataCase_ == 5) {
      output.writeMessage(5, (com.gbft.framework.data.ReportData) eventData_);
    }
    if (eventDataCase_ == 6) {
      output.writeMessage(6, (com.gbft.framework.data.MessageBlock) eventData_);
    }
    if (eventDataCase_ == 7) {
      output.writeInt32(
          7, (int)((java.lang.Integer) eventData_));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (eventType_ != com.gbft.framework.data.Event.EventType.INIT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, eventType_);
    }
    if (eventDataCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.gbft.framework.data.UnitData) eventData_);
    }
    if (eventDataCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.gbft.framework.data.ConfigData) eventData_);
    }
    if (eventDataCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.gbft.framework.data.PluginData) eventData_);
    }
    if (eventDataCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.gbft.framework.data.ReportData) eventData_);
    }
    if (eventDataCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (com.gbft.framework.data.MessageBlock) eventData_);
    }
    if (eventDataCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(
            7, (int)((java.lang.Integer) eventData_));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gbft.framework.data.Event)) {
      return super.equals(obj);
    }
    com.gbft.framework.data.Event other = (com.gbft.framework.data.Event) obj;

    if (eventType_ != other.eventType_) return false;
    if (!getEventDataCase().equals(other.getEventDataCase())) return false;
    switch (eventDataCase_) {
      case 2:
        if (!getUnitData()
            .equals(other.getUnitData())) return false;
        break;
      case 3:
        if (!getConfigData()
            .equals(other.getConfigData())) return false;
        break;
      case 4:
        if (!getPluginData()
            .equals(other.getPluginData())) return false;
        break;
      case 5:
        if (!getReportData()
            .equals(other.getReportData())) return false;
        break;
      case 6:
        if (!getMessageBlock()
            .equals(other.getMessageBlock())) return false;
        break;
      case 7:
        if (getTarget()
            != other.getTarget()) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EVENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + eventType_;
    switch (eventDataCase_) {
      case 2:
        hash = (37 * hash) + UNIT_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getUnitData().hashCode();
        break;
      case 3:
        hash = (37 * hash) + CONFIG_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getConfigData().hashCode();
        break;
      case 4:
        hash = (37 * hash) + PLUGIN_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getPluginData().hashCode();
        break;
      case 5:
        hash = (37 * hash) + REPORT_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getReportData().hashCode();
        break;
      case 6:
        hash = (37 * hash) + MESSAGE_BLOCK_FIELD_NUMBER;
        hash = (53 * hash) + getMessageBlock().hashCode();
        break;
      case 7:
        hash = (37 * hash) + TARGET_FIELD_NUMBER;
        hash = (53 * hash) + getTarget();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gbft.framework.data.Event parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.Event parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.Event parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.Event parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.Event parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.Event parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.Event parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.Event parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gbft.framework.data.Event parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.Event parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gbft.framework.data.Event parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.Event parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gbft.framework.data.Event prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Event}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Event)
      com.gbft.framework.data.EventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gbft.framework.data.Gbft.internal_static_Event_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gbft.framework.data.Gbft.internal_static_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gbft.framework.data.Event.class, com.gbft.framework.data.Event.Builder.class);
    }

    // Construct using com.gbft.framework.data.Event.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      eventType_ = 0;

      eventDataCase_ = 0;
      eventData_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gbft.framework.data.Gbft.internal_static_Event_descriptor;
    }

    @java.lang.Override
    public com.gbft.framework.data.Event getDefaultInstanceForType() {
      return com.gbft.framework.data.Event.getDefaultInstance();
    }

    @java.lang.Override
    public com.gbft.framework.data.Event build() {
      com.gbft.framework.data.Event result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gbft.framework.data.Event buildPartial() {
      com.gbft.framework.data.Event result = new com.gbft.framework.data.Event(this);
      result.eventType_ = eventType_;
      if (eventDataCase_ == 2) {
        if (unitDataBuilder_ == null) {
          result.eventData_ = eventData_;
        } else {
          result.eventData_ = unitDataBuilder_.build();
        }
      }
      if (eventDataCase_ == 3) {
        if (configDataBuilder_ == null) {
          result.eventData_ = eventData_;
        } else {
          result.eventData_ = configDataBuilder_.build();
        }
      }
      if (eventDataCase_ == 4) {
        if (pluginDataBuilder_ == null) {
          result.eventData_ = eventData_;
        } else {
          result.eventData_ = pluginDataBuilder_.build();
        }
      }
      if (eventDataCase_ == 5) {
        if (reportDataBuilder_ == null) {
          result.eventData_ = eventData_;
        } else {
          result.eventData_ = reportDataBuilder_.build();
        }
      }
      if (eventDataCase_ == 6) {
        if (messageBlockBuilder_ == null) {
          result.eventData_ = eventData_;
        } else {
          result.eventData_ = messageBlockBuilder_.build();
        }
      }
      if (eventDataCase_ == 7) {
        result.eventData_ = eventData_;
      }
      result.eventDataCase_ = eventDataCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gbft.framework.data.Event) {
        return mergeFrom((com.gbft.framework.data.Event)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gbft.framework.data.Event other) {
      if (other == com.gbft.framework.data.Event.getDefaultInstance()) return this;
      if (other.eventType_ != 0) {
        setEventTypeValue(other.getEventTypeValue());
      }
      switch (other.getEventDataCase()) {
        case UNIT_DATA: {
          mergeUnitData(other.getUnitData());
          break;
        }
        case CONFIG_DATA: {
          mergeConfigData(other.getConfigData());
          break;
        }
        case PLUGIN_DATA: {
          mergePluginData(other.getPluginData());
          break;
        }
        case REPORT_DATA: {
          mergeReportData(other.getReportData());
          break;
        }
        case MESSAGE_BLOCK: {
          mergeMessageBlock(other.getMessageBlock());
          break;
        }
        case TARGET: {
          setTarget(other.getTarget());
          break;
        }
        case EVENTDATA_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gbft.framework.data.Event parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gbft.framework.data.Event) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int eventDataCase_ = 0;
    private java.lang.Object eventData_;
    public EventDataCase
        getEventDataCase() {
      return EventDataCase.forNumber(
          eventDataCase_);
    }

    public Builder clearEventData() {
      eventDataCase_ = 0;
      eventData_ = null;
      onChanged();
      return this;
    }


    private int eventType_ = 0;
    /**
     * <code>.Event.EventType event_type = 1;</code>
     * @return The enum numeric value on the wire for eventType.
     */
    @java.lang.Override public int getEventTypeValue() {
      return eventType_;
    }
    /**
     * <code>.Event.EventType event_type = 1;</code>
     * @param value The enum numeric value on the wire for eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypeValue(int value) {
      
      eventType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.Event.EventType event_type = 1;</code>
     * @return The eventType.
     */
    @java.lang.Override
    public com.gbft.framework.data.Event.EventType getEventType() {
      @SuppressWarnings("deprecation")
      com.gbft.framework.data.Event.EventType result = com.gbft.framework.data.Event.EventType.valueOf(eventType_);
      return result == null ? com.gbft.framework.data.Event.EventType.UNRECOGNIZED : result;
    }
    /**
     * <code>.Event.EventType event_type = 1;</code>
     * @param value The eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventType(com.gbft.framework.data.Event.EventType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      eventType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.Event.EventType event_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventType() {
      
      eventType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.gbft.framework.data.UnitData, com.gbft.framework.data.UnitData.Builder, com.gbft.framework.data.UnitDataOrBuilder> unitDataBuilder_;
    /**
     * <code>.UnitData unit_data = 2;</code>
     * @return Whether the unitData field is set.
     */
    @java.lang.Override
    public boolean hasUnitData() {
      return eventDataCase_ == 2;
    }
    /**
     * <code>.UnitData unit_data = 2;</code>
     * @return The unitData.
     */
    @java.lang.Override
    public com.gbft.framework.data.UnitData getUnitData() {
      if (unitDataBuilder_ == null) {
        if (eventDataCase_ == 2) {
          return (com.gbft.framework.data.UnitData) eventData_;
        }
        return com.gbft.framework.data.UnitData.getDefaultInstance();
      } else {
        if (eventDataCase_ == 2) {
          return unitDataBuilder_.getMessage();
        }
        return com.gbft.framework.data.UnitData.getDefaultInstance();
      }
    }
    /**
     * <code>.UnitData unit_data = 2;</code>
     */
    public Builder setUnitData(com.gbft.framework.data.UnitData value) {
      if (unitDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        eventData_ = value;
        onChanged();
      } else {
        unitDataBuilder_.setMessage(value);
      }
      eventDataCase_ = 2;
      return this;
    }
    /**
     * <code>.UnitData unit_data = 2;</code>
     */
    public Builder setUnitData(
        com.gbft.framework.data.UnitData.Builder builderForValue) {
      if (unitDataBuilder_ == null) {
        eventData_ = builderForValue.build();
        onChanged();
      } else {
        unitDataBuilder_.setMessage(builderForValue.build());
      }
      eventDataCase_ = 2;
      return this;
    }
    /**
     * <code>.UnitData unit_data = 2;</code>
     */
    public Builder mergeUnitData(com.gbft.framework.data.UnitData value) {
      if (unitDataBuilder_ == null) {
        if (eventDataCase_ == 2 &&
            eventData_ != com.gbft.framework.data.UnitData.getDefaultInstance()) {
          eventData_ = com.gbft.framework.data.UnitData.newBuilder((com.gbft.framework.data.UnitData) eventData_)
              .mergeFrom(value).buildPartial();
        } else {
          eventData_ = value;
        }
        onChanged();
      } else {
        if (eventDataCase_ == 2) {
          unitDataBuilder_.mergeFrom(value);
        }
        unitDataBuilder_.setMessage(value);
      }
      eventDataCase_ = 2;
      return this;
    }
    /**
     * <code>.UnitData unit_data = 2;</code>
     */
    public Builder clearUnitData() {
      if (unitDataBuilder_ == null) {
        if (eventDataCase_ == 2) {
          eventDataCase_ = 0;
          eventData_ = null;
          onChanged();
        }
      } else {
        if (eventDataCase_ == 2) {
          eventDataCase_ = 0;
          eventData_ = null;
        }
        unitDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.UnitData unit_data = 2;</code>
     */
    public com.gbft.framework.data.UnitData.Builder getUnitDataBuilder() {
      return getUnitDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.UnitData unit_data = 2;</code>
     */
    @java.lang.Override
    public com.gbft.framework.data.UnitDataOrBuilder getUnitDataOrBuilder() {
      if ((eventDataCase_ == 2) && (unitDataBuilder_ != null)) {
        return unitDataBuilder_.getMessageOrBuilder();
      } else {
        if (eventDataCase_ == 2) {
          return (com.gbft.framework.data.UnitData) eventData_;
        }
        return com.gbft.framework.data.UnitData.getDefaultInstance();
      }
    }
    /**
     * <code>.UnitData unit_data = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gbft.framework.data.UnitData, com.gbft.framework.data.UnitData.Builder, com.gbft.framework.data.UnitDataOrBuilder> 
        getUnitDataFieldBuilder() {
      if (unitDataBuilder_ == null) {
        if (!(eventDataCase_ == 2)) {
          eventData_ = com.gbft.framework.data.UnitData.getDefaultInstance();
        }
        unitDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gbft.framework.data.UnitData, com.gbft.framework.data.UnitData.Builder, com.gbft.framework.data.UnitDataOrBuilder>(
                (com.gbft.framework.data.UnitData) eventData_,
                getParentForChildren(),
                isClean());
        eventData_ = null;
      }
      eventDataCase_ = 2;
      onChanged();;
      return unitDataBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.gbft.framework.data.ConfigData, com.gbft.framework.data.ConfigData.Builder, com.gbft.framework.data.ConfigDataOrBuilder> configDataBuilder_;
    /**
     * <code>.ConfigData config_data = 3;</code>
     * @return Whether the configData field is set.
     */
    @java.lang.Override
    public boolean hasConfigData() {
      return eventDataCase_ == 3;
    }
    /**
     * <code>.ConfigData config_data = 3;</code>
     * @return The configData.
     */
    @java.lang.Override
    public com.gbft.framework.data.ConfigData getConfigData() {
      if (configDataBuilder_ == null) {
        if (eventDataCase_ == 3) {
          return (com.gbft.framework.data.ConfigData) eventData_;
        }
        return com.gbft.framework.data.ConfigData.getDefaultInstance();
      } else {
        if (eventDataCase_ == 3) {
          return configDataBuilder_.getMessage();
        }
        return com.gbft.framework.data.ConfigData.getDefaultInstance();
      }
    }
    /**
     * <code>.ConfigData config_data = 3;</code>
     */
    public Builder setConfigData(com.gbft.framework.data.ConfigData value) {
      if (configDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        eventData_ = value;
        onChanged();
      } else {
        configDataBuilder_.setMessage(value);
      }
      eventDataCase_ = 3;
      return this;
    }
    /**
     * <code>.ConfigData config_data = 3;</code>
     */
    public Builder setConfigData(
        com.gbft.framework.data.ConfigData.Builder builderForValue) {
      if (configDataBuilder_ == null) {
        eventData_ = builderForValue.build();
        onChanged();
      } else {
        configDataBuilder_.setMessage(builderForValue.build());
      }
      eventDataCase_ = 3;
      return this;
    }
    /**
     * <code>.ConfigData config_data = 3;</code>
     */
    public Builder mergeConfigData(com.gbft.framework.data.ConfigData value) {
      if (configDataBuilder_ == null) {
        if (eventDataCase_ == 3 &&
            eventData_ != com.gbft.framework.data.ConfigData.getDefaultInstance()) {
          eventData_ = com.gbft.framework.data.ConfigData.newBuilder((com.gbft.framework.data.ConfigData) eventData_)
              .mergeFrom(value).buildPartial();
        } else {
          eventData_ = value;
        }
        onChanged();
      } else {
        if (eventDataCase_ == 3) {
          configDataBuilder_.mergeFrom(value);
        }
        configDataBuilder_.setMessage(value);
      }
      eventDataCase_ = 3;
      return this;
    }
    /**
     * <code>.ConfigData config_data = 3;</code>
     */
    public Builder clearConfigData() {
      if (configDataBuilder_ == null) {
        if (eventDataCase_ == 3) {
          eventDataCase_ = 0;
          eventData_ = null;
          onChanged();
        }
      } else {
        if (eventDataCase_ == 3) {
          eventDataCase_ = 0;
          eventData_ = null;
        }
        configDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ConfigData config_data = 3;</code>
     */
    public com.gbft.framework.data.ConfigData.Builder getConfigDataBuilder() {
      return getConfigDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.ConfigData config_data = 3;</code>
     */
    @java.lang.Override
    public com.gbft.framework.data.ConfigDataOrBuilder getConfigDataOrBuilder() {
      if ((eventDataCase_ == 3) && (configDataBuilder_ != null)) {
        return configDataBuilder_.getMessageOrBuilder();
      } else {
        if (eventDataCase_ == 3) {
          return (com.gbft.framework.data.ConfigData) eventData_;
        }
        return com.gbft.framework.data.ConfigData.getDefaultInstance();
      }
    }
    /**
     * <code>.ConfigData config_data = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gbft.framework.data.ConfigData, com.gbft.framework.data.ConfigData.Builder, com.gbft.framework.data.ConfigDataOrBuilder> 
        getConfigDataFieldBuilder() {
      if (configDataBuilder_ == null) {
        if (!(eventDataCase_ == 3)) {
          eventData_ = com.gbft.framework.data.ConfigData.getDefaultInstance();
        }
        configDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gbft.framework.data.ConfigData, com.gbft.framework.data.ConfigData.Builder, com.gbft.framework.data.ConfigDataOrBuilder>(
                (com.gbft.framework.data.ConfigData) eventData_,
                getParentForChildren(),
                isClean());
        eventData_ = null;
      }
      eventDataCase_ = 3;
      onChanged();;
      return configDataBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.gbft.framework.data.PluginData, com.gbft.framework.data.PluginData.Builder, com.gbft.framework.data.PluginDataOrBuilder> pluginDataBuilder_;
    /**
     * <code>.PluginData plugin_data = 4;</code>
     * @return Whether the pluginData field is set.
     */
    @java.lang.Override
    public boolean hasPluginData() {
      return eventDataCase_ == 4;
    }
    /**
     * <code>.PluginData plugin_data = 4;</code>
     * @return The pluginData.
     */
    @java.lang.Override
    public com.gbft.framework.data.PluginData getPluginData() {
      if (pluginDataBuilder_ == null) {
        if (eventDataCase_ == 4) {
          return (com.gbft.framework.data.PluginData) eventData_;
        }
        return com.gbft.framework.data.PluginData.getDefaultInstance();
      } else {
        if (eventDataCase_ == 4) {
          return pluginDataBuilder_.getMessage();
        }
        return com.gbft.framework.data.PluginData.getDefaultInstance();
      }
    }
    /**
     * <code>.PluginData plugin_data = 4;</code>
     */
    public Builder setPluginData(com.gbft.framework.data.PluginData value) {
      if (pluginDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        eventData_ = value;
        onChanged();
      } else {
        pluginDataBuilder_.setMessage(value);
      }
      eventDataCase_ = 4;
      return this;
    }
    /**
     * <code>.PluginData plugin_data = 4;</code>
     */
    public Builder setPluginData(
        com.gbft.framework.data.PluginData.Builder builderForValue) {
      if (pluginDataBuilder_ == null) {
        eventData_ = builderForValue.build();
        onChanged();
      } else {
        pluginDataBuilder_.setMessage(builderForValue.build());
      }
      eventDataCase_ = 4;
      return this;
    }
    /**
     * <code>.PluginData plugin_data = 4;</code>
     */
    public Builder mergePluginData(com.gbft.framework.data.PluginData value) {
      if (pluginDataBuilder_ == null) {
        if (eventDataCase_ == 4 &&
            eventData_ != com.gbft.framework.data.PluginData.getDefaultInstance()) {
          eventData_ = com.gbft.framework.data.PluginData.newBuilder((com.gbft.framework.data.PluginData) eventData_)
              .mergeFrom(value).buildPartial();
        } else {
          eventData_ = value;
        }
        onChanged();
      } else {
        if (eventDataCase_ == 4) {
          pluginDataBuilder_.mergeFrom(value);
        }
        pluginDataBuilder_.setMessage(value);
      }
      eventDataCase_ = 4;
      return this;
    }
    /**
     * <code>.PluginData plugin_data = 4;</code>
     */
    public Builder clearPluginData() {
      if (pluginDataBuilder_ == null) {
        if (eventDataCase_ == 4) {
          eventDataCase_ = 0;
          eventData_ = null;
          onChanged();
        }
      } else {
        if (eventDataCase_ == 4) {
          eventDataCase_ = 0;
          eventData_ = null;
        }
        pluginDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.PluginData plugin_data = 4;</code>
     */
    public com.gbft.framework.data.PluginData.Builder getPluginDataBuilder() {
      return getPluginDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.PluginData plugin_data = 4;</code>
     */
    @java.lang.Override
    public com.gbft.framework.data.PluginDataOrBuilder getPluginDataOrBuilder() {
      if ((eventDataCase_ == 4) && (pluginDataBuilder_ != null)) {
        return pluginDataBuilder_.getMessageOrBuilder();
      } else {
        if (eventDataCase_ == 4) {
          return (com.gbft.framework.data.PluginData) eventData_;
        }
        return com.gbft.framework.data.PluginData.getDefaultInstance();
      }
    }
    /**
     * <code>.PluginData plugin_data = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gbft.framework.data.PluginData, com.gbft.framework.data.PluginData.Builder, com.gbft.framework.data.PluginDataOrBuilder> 
        getPluginDataFieldBuilder() {
      if (pluginDataBuilder_ == null) {
        if (!(eventDataCase_ == 4)) {
          eventData_ = com.gbft.framework.data.PluginData.getDefaultInstance();
        }
        pluginDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gbft.framework.data.PluginData, com.gbft.framework.data.PluginData.Builder, com.gbft.framework.data.PluginDataOrBuilder>(
                (com.gbft.framework.data.PluginData) eventData_,
                getParentForChildren(),
                isClean());
        eventData_ = null;
      }
      eventDataCase_ = 4;
      onChanged();;
      return pluginDataBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.gbft.framework.data.ReportData, com.gbft.framework.data.ReportData.Builder, com.gbft.framework.data.ReportDataOrBuilder> reportDataBuilder_;
    /**
     * <code>.ReportData report_data = 5;</code>
     * @return Whether the reportData field is set.
     */
    @java.lang.Override
    public boolean hasReportData() {
      return eventDataCase_ == 5;
    }
    /**
     * <code>.ReportData report_data = 5;</code>
     * @return The reportData.
     */
    @java.lang.Override
    public com.gbft.framework.data.ReportData getReportData() {
      if (reportDataBuilder_ == null) {
        if (eventDataCase_ == 5) {
          return (com.gbft.framework.data.ReportData) eventData_;
        }
        return com.gbft.framework.data.ReportData.getDefaultInstance();
      } else {
        if (eventDataCase_ == 5) {
          return reportDataBuilder_.getMessage();
        }
        return com.gbft.framework.data.ReportData.getDefaultInstance();
      }
    }
    /**
     * <code>.ReportData report_data = 5;</code>
     */
    public Builder setReportData(com.gbft.framework.data.ReportData value) {
      if (reportDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        eventData_ = value;
        onChanged();
      } else {
        reportDataBuilder_.setMessage(value);
      }
      eventDataCase_ = 5;
      return this;
    }
    /**
     * <code>.ReportData report_data = 5;</code>
     */
    public Builder setReportData(
        com.gbft.framework.data.ReportData.Builder builderForValue) {
      if (reportDataBuilder_ == null) {
        eventData_ = builderForValue.build();
        onChanged();
      } else {
        reportDataBuilder_.setMessage(builderForValue.build());
      }
      eventDataCase_ = 5;
      return this;
    }
    /**
     * <code>.ReportData report_data = 5;</code>
     */
    public Builder mergeReportData(com.gbft.framework.data.ReportData value) {
      if (reportDataBuilder_ == null) {
        if (eventDataCase_ == 5 &&
            eventData_ != com.gbft.framework.data.ReportData.getDefaultInstance()) {
          eventData_ = com.gbft.framework.data.ReportData.newBuilder((com.gbft.framework.data.ReportData) eventData_)
              .mergeFrom(value).buildPartial();
        } else {
          eventData_ = value;
        }
        onChanged();
      } else {
        if (eventDataCase_ == 5) {
          reportDataBuilder_.mergeFrom(value);
        }
        reportDataBuilder_.setMessage(value);
      }
      eventDataCase_ = 5;
      return this;
    }
    /**
     * <code>.ReportData report_data = 5;</code>
     */
    public Builder clearReportData() {
      if (reportDataBuilder_ == null) {
        if (eventDataCase_ == 5) {
          eventDataCase_ = 0;
          eventData_ = null;
          onChanged();
        }
      } else {
        if (eventDataCase_ == 5) {
          eventDataCase_ = 0;
          eventData_ = null;
        }
        reportDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ReportData report_data = 5;</code>
     */
    public com.gbft.framework.data.ReportData.Builder getReportDataBuilder() {
      return getReportDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.ReportData report_data = 5;</code>
     */
    @java.lang.Override
    public com.gbft.framework.data.ReportDataOrBuilder getReportDataOrBuilder() {
      if ((eventDataCase_ == 5) && (reportDataBuilder_ != null)) {
        return reportDataBuilder_.getMessageOrBuilder();
      } else {
        if (eventDataCase_ == 5) {
          return (com.gbft.framework.data.ReportData) eventData_;
        }
        return com.gbft.framework.data.ReportData.getDefaultInstance();
      }
    }
    /**
     * <code>.ReportData report_data = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gbft.framework.data.ReportData, com.gbft.framework.data.ReportData.Builder, com.gbft.framework.data.ReportDataOrBuilder> 
        getReportDataFieldBuilder() {
      if (reportDataBuilder_ == null) {
        if (!(eventDataCase_ == 5)) {
          eventData_ = com.gbft.framework.data.ReportData.getDefaultInstance();
        }
        reportDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gbft.framework.data.ReportData, com.gbft.framework.data.ReportData.Builder, com.gbft.framework.data.ReportDataOrBuilder>(
                (com.gbft.framework.data.ReportData) eventData_,
                getParentForChildren(),
                isClean());
        eventData_ = null;
      }
      eventDataCase_ = 5;
      onChanged();;
      return reportDataBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.gbft.framework.data.MessageBlock, com.gbft.framework.data.MessageBlock.Builder, com.gbft.framework.data.MessageBlockOrBuilder> messageBlockBuilder_;
    /**
     * <code>.MessageBlock message_block = 6;</code>
     * @return Whether the messageBlock field is set.
     */
    @java.lang.Override
    public boolean hasMessageBlock() {
      return eventDataCase_ == 6;
    }
    /**
     * <code>.MessageBlock message_block = 6;</code>
     * @return The messageBlock.
     */
    @java.lang.Override
    public com.gbft.framework.data.MessageBlock getMessageBlock() {
      if (messageBlockBuilder_ == null) {
        if (eventDataCase_ == 6) {
          return (com.gbft.framework.data.MessageBlock) eventData_;
        }
        return com.gbft.framework.data.MessageBlock.getDefaultInstance();
      } else {
        if (eventDataCase_ == 6) {
          return messageBlockBuilder_.getMessage();
        }
        return com.gbft.framework.data.MessageBlock.getDefaultInstance();
      }
    }
    /**
     * <code>.MessageBlock message_block = 6;</code>
     */
    public Builder setMessageBlock(com.gbft.framework.data.MessageBlock value) {
      if (messageBlockBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        eventData_ = value;
        onChanged();
      } else {
        messageBlockBuilder_.setMessage(value);
      }
      eventDataCase_ = 6;
      return this;
    }
    /**
     * <code>.MessageBlock message_block = 6;</code>
     */
    public Builder setMessageBlock(
        com.gbft.framework.data.MessageBlock.Builder builderForValue) {
      if (messageBlockBuilder_ == null) {
        eventData_ = builderForValue.build();
        onChanged();
      } else {
        messageBlockBuilder_.setMessage(builderForValue.build());
      }
      eventDataCase_ = 6;
      return this;
    }
    /**
     * <code>.MessageBlock message_block = 6;</code>
     */
    public Builder mergeMessageBlock(com.gbft.framework.data.MessageBlock value) {
      if (messageBlockBuilder_ == null) {
        if (eventDataCase_ == 6 &&
            eventData_ != com.gbft.framework.data.MessageBlock.getDefaultInstance()) {
          eventData_ = com.gbft.framework.data.MessageBlock.newBuilder((com.gbft.framework.data.MessageBlock) eventData_)
              .mergeFrom(value).buildPartial();
        } else {
          eventData_ = value;
        }
        onChanged();
      } else {
        if (eventDataCase_ == 6) {
          messageBlockBuilder_.mergeFrom(value);
        }
        messageBlockBuilder_.setMessage(value);
      }
      eventDataCase_ = 6;
      return this;
    }
    /**
     * <code>.MessageBlock message_block = 6;</code>
     */
    public Builder clearMessageBlock() {
      if (messageBlockBuilder_ == null) {
        if (eventDataCase_ == 6) {
          eventDataCase_ = 0;
          eventData_ = null;
          onChanged();
        }
      } else {
        if (eventDataCase_ == 6) {
          eventDataCase_ = 0;
          eventData_ = null;
        }
        messageBlockBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.MessageBlock message_block = 6;</code>
     */
    public com.gbft.framework.data.MessageBlock.Builder getMessageBlockBuilder() {
      return getMessageBlockFieldBuilder().getBuilder();
    }
    /**
     * <code>.MessageBlock message_block = 6;</code>
     */
    @java.lang.Override
    public com.gbft.framework.data.MessageBlockOrBuilder getMessageBlockOrBuilder() {
      if ((eventDataCase_ == 6) && (messageBlockBuilder_ != null)) {
        return messageBlockBuilder_.getMessageOrBuilder();
      } else {
        if (eventDataCase_ == 6) {
          return (com.gbft.framework.data.MessageBlock) eventData_;
        }
        return com.gbft.framework.data.MessageBlock.getDefaultInstance();
      }
    }
    /**
     * <code>.MessageBlock message_block = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gbft.framework.data.MessageBlock, com.gbft.framework.data.MessageBlock.Builder, com.gbft.framework.data.MessageBlockOrBuilder> 
        getMessageBlockFieldBuilder() {
      if (messageBlockBuilder_ == null) {
        if (!(eventDataCase_ == 6)) {
          eventData_ = com.gbft.framework.data.MessageBlock.getDefaultInstance();
        }
        messageBlockBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gbft.framework.data.MessageBlock, com.gbft.framework.data.MessageBlock.Builder, com.gbft.framework.data.MessageBlockOrBuilder>(
                (com.gbft.framework.data.MessageBlock) eventData_,
                getParentForChildren(),
                isClean());
        eventData_ = null;
      }
      eventDataCase_ = 6;
      onChanged();;
      return messageBlockBuilder_;
    }

    /**
     * <code>int32 target = 7;</code>
     * @return The target.
     */
    public int getTarget() {
      if (eventDataCase_ == 7) {
        return (java.lang.Integer) eventData_;
      }
      return 0;
    }
    /**
     * <code>int32 target = 7;</code>
     * @param value The target to set.
     * @return This builder for chaining.
     */
    public Builder setTarget(int value) {
      eventDataCase_ = 7;
      eventData_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 target = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTarget() {
      if (eventDataCase_ == 7) {
        eventDataCase_ = 0;
        eventData_ = null;
        onChanged();
      }
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Event)
  }

  // @@protoc_insertion_point(class_scope:Event)
  private static final com.gbft.framework.data.Event DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gbft.framework.data.Event();
  }

  public static com.gbft.framework.data.Event getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Event>
      PARSER = new com.google.protobuf.AbstractParser<Event>() {
    @java.lang.Override
    public Event parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Event(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Event> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Event> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gbft.framework.data.Event getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

