// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbft.proto

package com.gbft.framework.data;

public interface FaultDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FaultData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 blocked_targets = 1;</code>
   * @return A list containing the blockedTargets.
   */
  java.util.List<java.lang.Integer> getBlockedTargetsList();
  /**
   * <code>repeated int32 blocked_targets = 1;</code>
   * @return The count of blockedTargets.
   */
  int getBlockedTargetsCount();
  /**
   * <code>repeated int32 blocked_targets = 1;</code>
   * @param index The index of the element to return.
   * @return The blockedTargets at the given index.
   */
  int getBlockedTargets(int index);

  /**
   * <code>repeated int32 delayed_targets = 2;</code>
   * @return A list containing the delayedTargets.
   */
  java.util.List<java.lang.Integer> getDelayedTargetsList();
  /**
   * <code>repeated int32 delayed_targets = 2;</code>
   * @return The count of delayedTargets.
   */
  int getDelayedTargetsCount();
  /**
   * <code>repeated int32 delayed_targets = 2;</code>
   * @param index The index of the element to return.
   * @return The delayedTargets at the given index.
   */
  int getDelayedTargets(int index);

  /**
   * <code>int64 delay = 3;</code>
   * @return The delay.
   */
  long getDelay();
}
