// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbft.proto

package com.gbft.framework.data;

/**
 * Protobuf type {@code FetchData}
 */
public final class FetchData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FetchData)
    FetchDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FetchData.newBuilder() to construct.
  private FetchData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FetchData() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FetchData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FetchData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            isRequest_ = input.readBool();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              serviceState_ = com.google.protobuf.MapField.newMapField(
                  ServiceStateDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
            serviceState__ = input.readMessage(
                ServiceStateDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            serviceState_.getMutableMap().put(
                serviceState__.getKey(), serviceState__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gbft.framework.data.Gbft.internal_static_FetchData_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 2:
        return internalGetServiceState();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gbft.framework.data.Gbft.internal_static_FetchData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gbft.framework.data.FetchData.class, com.gbft.framework.data.FetchData.Builder.class);
  }

  public static final int IS_REQUEST_FIELD_NUMBER = 1;
  private boolean isRequest_;
  /**
   * <code>bool is_request = 1;</code>
   * @return The isRequest.
   */
  @java.lang.Override
  public boolean getIsRequest() {
    return isRequest_;
  }

  public static final int SERVICE_STATE_FIELD_NUMBER = 2;
  private static final class ServiceStateDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, java.lang.Integer> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, java.lang.Integer>newDefaultInstance(
                com.gbft.framework.data.Gbft.internal_static_FetchData_ServiceStateEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.INT32,
                0);
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, java.lang.Integer> serviceState_;
  private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
  internalGetServiceState() {
    if (serviceState_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ServiceStateDefaultEntryHolder.defaultEntry);
    }
    return serviceState_;
  }

  public int getServiceStateCount() {
    return internalGetServiceState().getMap().size();
  }
  /**
   * <code>map&lt;int32, int32&gt; service_state = 2;</code>
   */

  @java.lang.Override
  public boolean containsServiceState(
      int key) {
    
    return internalGetServiceState().getMap().containsKey(key);
  }
  /**
   * Use {@link #getServiceStateMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, java.lang.Integer> getServiceState() {
    return getServiceStateMap();
  }
  /**
   * <code>map&lt;int32, int32&gt; service_state = 2;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.Integer, java.lang.Integer> getServiceStateMap() {
    return internalGetServiceState().getMap();
  }
  /**
   * <code>map&lt;int32, int32&gt; service_state = 2;</code>
   */
  @java.lang.Override

  public int getServiceStateOrDefault(
      int key,
      int defaultValue) {
    
    java.util.Map<java.lang.Integer, java.lang.Integer> map =
        internalGetServiceState().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int32, int32&gt; service_state = 2;</code>
   */
  @java.lang.Override

  public int getServiceStateOrThrow(
      int key) {
    
    java.util.Map<java.lang.Integer, java.lang.Integer> map =
        internalGetServiceState().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isRequest_ != false) {
      output.writeBool(1, isRequest_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeIntegerMapTo(
        output,
        internalGetServiceState(),
        ServiceStateDefaultEntryHolder.defaultEntry,
        2);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isRequest_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isRequest_);
    }
    for (java.util.Map.Entry<java.lang.Integer, java.lang.Integer> entry
         : internalGetServiceState().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
      serviceState__ = ServiceStateDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, serviceState__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gbft.framework.data.FetchData)) {
      return super.equals(obj);
    }
    com.gbft.framework.data.FetchData other = (com.gbft.framework.data.FetchData) obj;

    if (getIsRequest()
        != other.getIsRequest()) return false;
    if (!internalGetServiceState().equals(
        other.internalGetServiceState())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IS_REQUEST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsRequest());
    if (!internalGetServiceState().getMap().isEmpty()) {
      hash = (37 * hash) + SERVICE_STATE_FIELD_NUMBER;
      hash = (53 * hash) + internalGetServiceState().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gbft.framework.data.FetchData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.FetchData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.FetchData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.FetchData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.FetchData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.FetchData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.FetchData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.FetchData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gbft.framework.data.FetchData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.FetchData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gbft.framework.data.FetchData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.FetchData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gbft.framework.data.FetchData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FetchData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FetchData)
      com.gbft.framework.data.FetchDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gbft.framework.data.Gbft.internal_static_FetchData_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetServiceState();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableServiceState();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gbft.framework.data.Gbft.internal_static_FetchData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gbft.framework.data.FetchData.class, com.gbft.framework.data.FetchData.Builder.class);
    }

    // Construct using com.gbft.framework.data.FetchData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      isRequest_ = false;

      internalGetMutableServiceState().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gbft.framework.data.Gbft.internal_static_FetchData_descriptor;
    }

    @java.lang.Override
    public com.gbft.framework.data.FetchData getDefaultInstanceForType() {
      return com.gbft.framework.data.FetchData.getDefaultInstance();
    }

    @java.lang.Override
    public com.gbft.framework.data.FetchData build() {
      com.gbft.framework.data.FetchData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gbft.framework.data.FetchData buildPartial() {
      com.gbft.framework.data.FetchData result = new com.gbft.framework.data.FetchData(this);
      int from_bitField0_ = bitField0_;
      result.isRequest_ = isRequest_;
      result.serviceState_ = internalGetServiceState();
      result.serviceState_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gbft.framework.data.FetchData) {
        return mergeFrom((com.gbft.framework.data.FetchData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gbft.framework.data.FetchData other) {
      if (other == com.gbft.framework.data.FetchData.getDefaultInstance()) return this;
      if (other.getIsRequest() != false) {
        setIsRequest(other.getIsRequest());
      }
      internalGetMutableServiceState().mergeFrom(
          other.internalGetServiceState());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gbft.framework.data.FetchData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gbft.framework.data.FetchData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean isRequest_ ;
    /**
     * <code>bool is_request = 1;</code>
     * @return The isRequest.
     */
    @java.lang.Override
    public boolean getIsRequest() {
      return isRequest_;
    }
    /**
     * <code>bool is_request = 1;</code>
     * @param value The isRequest to set.
     * @return This builder for chaining.
     */
    public Builder setIsRequest(boolean value) {
      
      isRequest_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_request = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsRequest() {
      
      isRequest_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Integer> serviceState_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetServiceState() {
      if (serviceState_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ServiceStateDefaultEntryHolder.defaultEntry);
      }
      return serviceState_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetMutableServiceState() {
      onChanged();;
      if (serviceState_ == null) {
        serviceState_ = com.google.protobuf.MapField.newMapField(
            ServiceStateDefaultEntryHolder.defaultEntry);
      }
      if (!serviceState_.isMutable()) {
        serviceState_ = serviceState_.copy();
      }
      return serviceState_;
    }

    public int getServiceStateCount() {
      return internalGetServiceState().getMap().size();
    }
    /**
     * <code>map&lt;int32, int32&gt; service_state = 2;</code>
     */

    @java.lang.Override
    public boolean containsServiceState(
        int key) {
      
      return internalGetServiceState().getMap().containsKey(key);
    }
    /**
     * Use {@link #getServiceStateMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer> getServiceState() {
      return getServiceStateMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; service_state = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Integer, java.lang.Integer> getServiceStateMap() {
      return internalGetServiceState().getMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; service_state = 2;</code>
     */
    @java.lang.Override

    public int getServiceStateOrDefault(
        int key,
        int defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetServiceState().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, int32&gt; service_state = 2;</code>
     */
    @java.lang.Override

    public int getServiceStateOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetServiceState().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearServiceState() {
      internalGetMutableServiceState().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int32, int32&gt; service_state = 2;</code>
     */

    public Builder removeServiceState(
        int key) {
      
      internalGetMutableServiceState().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer>
    getMutableServiceState() {
      return internalGetMutableServiceState().getMutableMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; service_state = 2;</code>
     */
    public Builder putServiceState(
        int key,
        int value) {
      
      
      internalGetMutableServiceState().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;int32, int32&gt; service_state = 2;</code>
     */

    public Builder putAllServiceState(
        java.util.Map<java.lang.Integer, java.lang.Integer> values) {
      internalGetMutableServiceState().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FetchData)
  }

  // @@protoc_insertion_point(class_scope:FetchData)
  private static final com.gbft.framework.data.FetchData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gbft.framework.data.FetchData();
  }

  public static com.gbft.framework.data.FetchData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FetchData>
      PARSER = new com.google.protobuf.AbstractParser<FetchData>() {
    @java.lang.Override
    public FetchData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FetchData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FetchData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FetchData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gbft.framework.data.FetchData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

