// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbft.proto

package com.gbft.framework.data;

public interface FetchDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FetchData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool is_request = 1;</code>
   * @return The isRequest.
   */
  boolean getIsRequest();

  /**
   * <code>map&lt;int32, int32&gt; service_state = 2;</code>
   */
  int getServiceStateCount();
  /**
   * <code>map&lt;int32, int32&gt; service_state = 2;</code>
   */
  boolean containsServiceState(
      int key);
  /**
   * Use {@link #getServiceStateMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, java.lang.Integer>
  getServiceState();
  /**
   * <code>map&lt;int32, int32&gt; service_state = 2;</code>
   */
  java.util.Map<java.lang.Integer, java.lang.Integer>
  getServiceStateMap();
  /**
   * <code>map&lt;int32, int32&gt; service_state = 2;</code>
   */

  int getServiceStateOrDefault(
      int key,
      int defaultValue);
  /**
   * <code>map&lt;int32, int32&gt; service_state = 2;</code>
   */

  int getServiceStateOrThrow(
      int key);
}
