// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbft.proto

package com.gbft.framework.data;

/**
 * Protobuf type {@code LearningData}
 */
public final class LearningData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:LearningData)
    LearningDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LearningData.newBuilder() to construct.
  private LearningData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LearningData() {
    nextProtocol_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LearningData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LearningData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              report_ = com.google.protobuf.MapField.newMapField(
                  ReportDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Float>
            report__ = input.readMessage(
                ReportDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            report_.getMutableMap().put(
                report__.getKey(), report__.getValue());
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            nextProtocol_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gbft.framework.data.Gbft.internal_static_LearningData_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetReport();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gbft.framework.data.Gbft.internal_static_LearningData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gbft.framework.data.LearningData.class, com.gbft.framework.data.LearningData.Builder.class);
  }

  public static final int REPORT_FIELD_NUMBER = 1;
  private static final class ReportDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, java.lang.Float> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, java.lang.Float>newDefaultInstance(
                com.gbft.framework.data.Gbft.internal_static_LearningData_ReportEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.FLOAT,
                0F);
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, java.lang.Float> report_;
  private com.google.protobuf.MapField<java.lang.Integer, java.lang.Float>
  internalGetReport() {
    if (report_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ReportDefaultEntryHolder.defaultEntry);
    }
    return report_;
  }

  public int getReportCount() {
    return internalGetReport().getMap().size();
  }
  /**
   * <code>map&lt;int32, float&gt; report = 1;</code>
   */

  @java.lang.Override
  public boolean containsReport(
      int key) {
    
    return internalGetReport().getMap().containsKey(key);
  }
  /**
   * Use {@link #getReportMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, java.lang.Float> getReport() {
    return getReportMap();
  }
  /**
   * <code>map&lt;int32, float&gt; report = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.Integer, java.lang.Float> getReportMap() {
    return internalGetReport().getMap();
  }
  /**
   * <code>map&lt;int32, float&gt; report = 1;</code>
   */
  @java.lang.Override

  public float getReportOrDefault(
      int key,
      float defaultValue) {
    
    java.util.Map<java.lang.Integer, java.lang.Float> map =
        internalGetReport().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int32, float&gt; report = 1;</code>
   */
  @java.lang.Override

  public float getReportOrThrow(
      int key) {
    
    java.util.Map<java.lang.Integer, java.lang.Float> map =
        internalGetReport().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int NEXT_PROTOCOL_FIELD_NUMBER = 2;
  private volatile java.lang.Object nextProtocol_;
  /**
   * <code>string next_protocol = 2;</code>
   * @return The nextProtocol.
   */
  @java.lang.Override
  public java.lang.String getNextProtocol() {
    java.lang.Object ref = nextProtocol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nextProtocol_ = s;
      return s;
    }
  }
  /**
   * <code>string next_protocol = 2;</code>
   * @return The bytes for nextProtocol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNextProtocolBytes() {
    java.lang.Object ref = nextProtocol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nextProtocol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeIntegerMapTo(
        output,
        internalGetReport(),
        ReportDefaultEntryHolder.defaultEntry,
        1);
    if (!getNextProtocolBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nextProtocol_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.Integer, java.lang.Float> entry
         : internalGetReport().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Float>
      report__ = ReportDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, report__);
    }
    if (!getNextProtocolBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nextProtocol_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gbft.framework.data.LearningData)) {
      return super.equals(obj);
    }
    com.gbft.framework.data.LearningData other = (com.gbft.framework.data.LearningData) obj;

    if (!internalGetReport().equals(
        other.internalGetReport())) return false;
    if (!getNextProtocol()
        .equals(other.getNextProtocol())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetReport().getMap().isEmpty()) {
      hash = (37 * hash) + REPORT_FIELD_NUMBER;
      hash = (53 * hash) + internalGetReport().hashCode();
    }
    hash = (37 * hash) + NEXT_PROTOCOL_FIELD_NUMBER;
    hash = (53 * hash) + getNextProtocol().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gbft.framework.data.LearningData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.LearningData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.LearningData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.LearningData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.LearningData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.LearningData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.LearningData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.LearningData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gbft.framework.data.LearningData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.LearningData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gbft.framework.data.LearningData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.LearningData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gbft.framework.data.LearningData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code LearningData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:LearningData)
      com.gbft.framework.data.LearningDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gbft.framework.data.Gbft.internal_static_LearningData_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetReport();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableReport();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gbft.framework.data.Gbft.internal_static_LearningData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gbft.framework.data.LearningData.class, com.gbft.framework.data.LearningData.Builder.class);
    }

    // Construct using com.gbft.framework.data.LearningData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableReport().clear();
      nextProtocol_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gbft.framework.data.Gbft.internal_static_LearningData_descriptor;
    }

    @java.lang.Override
    public com.gbft.framework.data.LearningData getDefaultInstanceForType() {
      return com.gbft.framework.data.LearningData.getDefaultInstance();
    }

    @java.lang.Override
    public com.gbft.framework.data.LearningData build() {
      com.gbft.framework.data.LearningData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gbft.framework.data.LearningData buildPartial() {
      com.gbft.framework.data.LearningData result = new com.gbft.framework.data.LearningData(this);
      int from_bitField0_ = bitField0_;
      result.report_ = internalGetReport();
      result.report_.makeImmutable();
      result.nextProtocol_ = nextProtocol_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gbft.framework.data.LearningData) {
        return mergeFrom((com.gbft.framework.data.LearningData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gbft.framework.data.LearningData other) {
      if (other == com.gbft.framework.data.LearningData.getDefaultInstance()) return this;
      internalGetMutableReport().mergeFrom(
          other.internalGetReport());
      if (!other.getNextProtocol().isEmpty()) {
        nextProtocol_ = other.nextProtocol_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gbft.framework.data.LearningData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gbft.framework.data.LearningData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Float> report_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Float>
    internalGetReport() {
      if (report_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ReportDefaultEntryHolder.defaultEntry);
      }
      return report_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Float>
    internalGetMutableReport() {
      onChanged();;
      if (report_ == null) {
        report_ = com.google.protobuf.MapField.newMapField(
            ReportDefaultEntryHolder.defaultEntry);
      }
      if (!report_.isMutable()) {
        report_ = report_.copy();
      }
      return report_;
    }

    public int getReportCount() {
      return internalGetReport().getMap().size();
    }
    /**
     * <code>map&lt;int32, float&gt; report = 1;</code>
     */

    @java.lang.Override
    public boolean containsReport(
        int key) {
      
      return internalGetReport().getMap().containsKey(key);
    }
    /**
     * Use {@link #getReportMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Float> getReport() {
      return getReportMap();
    }
    /**
     * <code>map&lt;int32, float&gt; report = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Integer, java.lang.Float> getReportMap() {
      return internalGetReport().getMap();
    }
    /**
     * <code>map&lt;int32, float&gt; report = 1;</code>
     */
    @java.lang.Override

    public float getReportOrDefault(
        int key,
        float defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Float> map =
          internalGetReport().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, float&gt; report = 1;</code>
     */
    @java.lang.Override

    public float getReportOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Float> map =
          internalGetReport().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearReport() {
      internalGetMutableReport().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int32, float&gt; report = 1;</code>
     */

    public Builder removeReport(
        int key) {
      
      internalGetMutableReport().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Float>
    getMutableReport() {
      return internalGetMutableReport().getMutableMap();
    }
    /**
     * <code>map&lt;int32, float&gt; report = 1;</code>
     */
    public Builder putReport(
        int key,
        float value) {
      
      
      internalGetMutableReport().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;int32, float&gt; report = 1;</code>
     */

    public Builder putAllReport(
        java.util.Map<java.lang.Integer, java.lang.Float> values) {
      internalGetMutableReport().getMutableMap()
          .putAll(values);
      return this;
    }

    private java.lang.Object nextProtocol_ = "";
    /**
     * <code>string next_protocol = 2;</code>
     * @return The nextProtocol.
     */
    public java.lang.String getNextProtocol() {
      java.lang.Object ref = nextProtocol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nextProtocol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string next_protocol = 2;</code>
     * @return The bytes for nextProtocol.
     */
    public com.google.protobuf.ByteString
        getNextProtocolBytes() {
      java.lang.Object ref = nextProtocol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nextProtocol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string next_protocol = 2;</code>
     * @param value The nextProtocol to set.
     * @return This builder for chaining.
     */
    public Builder setNextProtocol(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nextProtocol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string next_protocol = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNextProtocol() {
      
      nextProtocol_ = getDefaultInstance().getNextProtocol();
      onChanged();
      return this;
    }
    /**
     * <code>string next_protocol = 2;</code>
     * @param value The bytes for nextProtocol to set.
     * @return This builder for chaining.
     */
    public Builder setNextProtocolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nextProtocol_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:LearningData)
  }

  // @@protoc_insertion_point(class_scope:LearningData)
  private static final com.gbft.framework.data.LearningData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gbft.framework.data.LearningData();
  }

  public static com.gbft.framework.data.LearningData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LearningData>
      PARSER = new com.google.protobuf.AbstractParser<LearningData>() {
    @java.lang.Override
    public LearningData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LearningData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LearningData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LearningData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gbft.framework.data.LearningData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

