// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbft.proto

package com.gbft.framework.data;

/**
 * Protobuf type {@code MessageBlock}
 */
public final class MessageBlock extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MessageBlock)
    MessageBlockOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageBlock.newBuilder() to construct.
  private MessageBlock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageBlock() {
    messageData_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageBlock();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MessageBlock(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 50: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              messageData_ = new java.util.ArrayList<com.gbft.framework.data.MessageData>();
              mutable_bitField0_ |= 0x00000001;
            }
            messageData_.add(
                input.readMessage(com.gbft.framework.data.MessageData.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        messageData_ = java.util.Collections.unmodifiableList(messageData_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gbft.framework.data.Gbft.internal_static_MessageBlock_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gbft.framework.data.Gbft.internal_static_MessageBlock_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gbft.framework.data.MessageBlock.class, com.gbft.framework.data.MessageBlock.Builder.class);
  }

  public static final int MESSAGE_DATA_FIELD_NUMBER = 6;
  private java.util.List<com.gbft.framework.data.MessageData> messageData_;
  /**
   * <code>repeated .MessageData message_data = 6;</code>
   */
  @java.lang.Override
  public java.util.List<com.gbft.framework.data.MessageData> getMessageDataList() {
    return messageData_;
  }
  /**
   * <code>repeated .MessageData message_data = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.gbft.framework.data.MessageDataOrBuilder> 
      getMessageDataOrBuilderList() {
    return messageData_;
  }
  /**
   * <code>repeated .MessageData message_data = 6;</code>
   */
  @java.lang.Override
  public int getMessageDataCount() {
    return messageData_.size();
  }
  /**
   * <code>repeated .MessageData message_data = 6;</code>
   */
  @java.lang.Override
  public com.gbft.framework.data.MessageData getMessageData(int index) {
    return messageData_.get(index);
  }
  /**
   * <code>repeated .MessageData message_data = 6;</code>
   */
  @java.lang.Override
  public com.gbft.framework.data.MessageDataOrBuilder getMessageDataOrBuilder(
      int index) {
    return messageData_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < messageData_.size(); i++) {
      output.writeMessage(6, messageData_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < messageData_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, messageData_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gbft.framework.data.MessageBlock)) {
      return super.equals(obj);
    }
    com.gbft.framework.data.MessageBlock other = (com.gbft.framework.data.MessageBlock) obj;

    if (!getMessageDataList()
        .equals(other.getMessageDataList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMessageDataCount() > 0) {
      hash = (37 * hash) + MESSAGE_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getMessageDataList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gbft.framework.data.MessageBlock parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.MessageBlock parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.MessageBlock parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.MessageBlock parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.MessageBlock parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.MessageBlock parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.MessageBlock parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.MessageBlock parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gbft.framework.data.MessageBlock parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.MessageBlock parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gbft.framework.data.MessageBlock parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.MessageBlock parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gbft.framework.data.MessageBlock prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MessageBlock}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MessageBlock)
      com.gbft.framework.data.MessageBlockOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gbft.framework.data.Gbft.internal_static_MessageBlock_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gbft.framework.data.Gbft.internal_static_MessageBlock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gbft.framework.data.MessageBlock.class, com.gbft.framework.data.MessageBlock.Builder.class);
    }

    // Construct using com.gbft.framework.data.MessageBlock.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMessageDataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (messageDataBuilder_ == null) {
        messageData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        messageDataBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gbft.framework.data.Gbft.internal_static_MessageBlock_descriptor;
    }

    @java.lang.Override
    public com.gbft.framework.data.MessageBlock getDefaultInstanceForType() {
      return com.gbft.framework.data.MessageBlock.getDefaultInstance();
    }

    @java.lang.Override
    public com.gbft.framework.data.MessageBlock build() {
      com.gbft.framework.data.MessageBlock result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gbft.framework.data.MessageBlock buildPartial() {
      com.gbft.framework.data.MessageBlock result = new com.gbft.framework.data.MessageBlock(this);
      int from_bitField0_ = bitField0_;
      if (messageDataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          messageData_ = java.util.Collections.unmodifiableList(messageData_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.messageData_ = messageData_;
      } else {
        result.messageData_ = messageDataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gbft.framework.data.MessageBlock) {
        return mergeFrom((com.gbft.framework.data.MessageBlock)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gbft.framework.data.MessageBlock other) {
      if (other == com.gbft.framework.data.MessageBlock.getDefaultInstance()) return this;
      if (messageDataBuilder_ == null) {
        if (!other.messageData_.isEmpty()) {
          if (messageData_.isEmpty()) {
            messageData_ = other.messageData_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMessageDataIsMutable();
            messageData_.addAll(other.messageData_);
          }
          onChanged();
        }
      } else {
        if (!other.messageData_.isEmpty()) {
          if (messageDataBuilder_.isEmpty()) {
            messageDataBuilder_.dispose();
            messageDataBuilder_ = null;
            messageData_ = other.messageData_;
            bitField0_ = (bitField0_ & ~0x00000001);
            messageDataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMessageDataFieldBuilder() : null;
          } else {
            messageDataBuilder_.addAllMessages(other.messageData_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gbft.framework.data.MessageBlock parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gbft.framework.data.MessageBlock) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.gbft.framework.data.MessageData> messageData_ =
      java.util.Collections.emptyList();
    private void ensureMessageDataIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        messageData_ = new java.util.ArrayList<com.gbft.framework.data.MessageData>(messageData_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.gbft.framework.data.MessageData, com.gbft.framework.data.MessageData.Builder, com.gbft.framework.data.MessageDataOrBuilder> messageDataBuilder_;

    /**
     * <code>repeated .MessageData message_data = 6;</code>
     */
    public java.util.List<com.gbft.framework.data.MessageData> getMessageDataList() {
      if (messageDataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(messageData_);
      } else {
        return messageDataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .MessageData message_data = 6;</code>
     */
    public int getMessageDataCount() {
      if (messageDataBuilder_ == null) {
        return messageData_.size();
      } else {
        return messageDataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .MessageData message_data = 6;</code>
     */
    public com.gbft.framework.data.MessageData getMessageData(int index) {
      if (messageDataBuilder_ == null) {
        return messageData_.get(index);
      } else {
        return messageDataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .MessageData message_data = 6;</code>
     */
    public Builder setMessageData(
        int index, com.gbft.framework.data.MessageData value) {
      if (messageDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageDataIsMutable();
        messageData_.set(index, value);
        onChanged();
      } else {
        messageDataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MessageData message_data = 6;</code>
     */
    public Builder setMessageData(
        int index, com.gbft.framework.data.MessageData.Builder builderForValue) {
      if (messageDataBuilder_ == null) {
        ensureMessageDataIsMutable();
        messageData_.set(index, builderForValue.build());
        onChanged();
      } else {
        messageDataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MessageData message_data = 6;</code>
     */
    public Builder addMessageData(com.gbft.framework.data.MessageData value) {
      if (messageDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageDataIsMutable();
        messageData_.add(value);
        onChanged();
      } else {
        messageDataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .MessageData message_data = 6;</code>
     */
    public Builder addMessageData(
        int index, com.gbft.framework.data.MessageData value) {
      if (messageDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageDataIsMutable();
        messageData_.add(index, value);
        onChanged();
      } else {
        messageDataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MessageData message_data = 6;</code>
     */
    public Builder addMessageData(
        com.gbft.framework.data.MessageData.Builder builderForValue) {
      if (messageDataBuilder_ == null) {
        ensureMessageDataIsMutable();
        messageData_.add(builderForValue.build());
        onChanged();
      } else {
        messageDataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MessageData message_data = 6;</code>
     */
    public Builder addMessageData(
        int index, com.gbft.framework.data.MessageData.Builder builderForValue) {
      if (messageDataBuilder_ == null) {
        ensureMessageDataIsMutable();
        messageData_.add(index, builderForValue.build());
        onChanged();
      } else {
        messageDataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MessageData message_data = 6;</code>
     */
    public Builder addAllMessageData(
        java.lang.Iterable<? extends com.gbft.framework.data.MessageData> values) {
      if (messageDataBuilder_ == null) {
        ensureMessageDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, messageData_);
        onChanged();
      } else {
        messageDataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .MessageData message_data = 6;</code>
     */
    public Builder clearMessageData() {
      if (messageDataBuilder_ == null) {
        messageData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        messageDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .MessageData message_data = 6;</code>
     */
    public Builder removeMessageData(int index) {
      if (messageDataBuilder_ == null) {
        ensureMessageDataIsMutable();
        messageData_.remove(index);
        onChanged();
      } else {
        messageDataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .MessageData message_data = 6;</code>
     */
    public com.gbft.framework.data.MessageData.Builder getMessageDataBuilder(
        int index) {
      return getMessageDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .MessageData message_data = 6;</code>
     */
    public com.gbft.framework.data.MessageDataOrBuilder getMessageDataOrBuilder(
        int index) {
      if (messageDataBuilder_ == null) {
        return messageData_.get(index);  } else {
        return messageDataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .MessageData message_data = 6;</code>
     */
    public java.util.List<? extends com.gbft.framework.data.MessageDataOrBuilder> 
         getMessageDataOrBuilderList() {
      if (messageDataBuilder_ != null) {
        return messageDataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(messageData_);
      }
    }
    /**
     * <code>repeated .MessageData message_data = 6;</code>
     */
    public com.gbft.framework.data.MessageData.Builder addMessageDataBuilder() {
      return getMessageDataFieldBuilder().addBuilder(
          com.gbft.framework.data.MessageData.getDefaultInstance());
    }
    /**
     * <code>repeated .MessageData message_data = 6;</code>
     */
    public com.gbft.framework.data.MessageData.Builder addMessageDataBuilder(
        int index) {
      return getMessageDataFieldBuilder().addBuilder(
          index, com.gbft.framework.data.MessageData.getDefaultInstance());
    }
    /**
     * <code>repeated .MessageData message_data = 6;</code>
     */
    public java.util.List<com.gbft.framework.data.MessageData.Builder> 
         getMessageDataBuilderList() {
      return getMessageDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.gbft.framework.data.MessageData, com.gbft.framework.data.MessageData.Builder, com.gbft.framework.data.MessageDataOrBuilder> 
        getMessageDataFieldBuilder() {
      if (messageDataBuilder_ == null) {
        messageDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.gbft.framework.data.MessageData, com.gbft.framework.data.MessageData.Builder, com.gbft.framework.data.MessageDataOrBuilder>(
                messageData_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        messageData_ = null;
      }
      return messageDataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MessageBlock)
  }

  // @@protoc_insertion_point(class_scope:MessageBlock)
  private static final com.gbft.framework.data.MessageBlock DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gbft.framework.data.MessageBlock();
  }

  public static com.gbft.framework.data.MessageBlock getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageBlock>
      PARSER = new com.google.protobuf.AbstractParser<MessageBlock>() {
    @java.lang.Override
    public MessageBlock parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MessageBlock(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MessageBlock> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageBlock> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gbft.framework.data.MessageBlock getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

