// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbft.proto

package com.gbft.framework.data;

public interface MessageBlockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageBlock)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .MessageData message_data = 6;</code>
   */
  java.util.List<com.gbft.framework.data.MessageData> 
      getMessageDataList();
  /**
   * <code>repeated .MessageData message_data = 6;</code>
   */
  com.gbft.framework.data.MessageData getMessageData(int index);
  /**
   * <code>repeated .MessageData message_data = 6;</code>
   */
  int getMessageDataCount();
  /**
   * <code>repeated .MessageData message_data = 6;</code>
   */
  java.util.List<? extends com.gbft.framework.data.MessageDataOrBuilder> 
      getMessageDataOrBuilderList();
  /**
   * <code>repeated .MessageData message_data = 6;</code>
   */
  com.gbft.framework.data.MessageDataOrBuilder getMessageDataOrBuilder(
      int index);
}
