// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbft.proto

package com.gbft.framework.data;

public interface MessageDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 sequence_num = 1;</code>
   * @return The sequenceNum.
   */
  long getSequenceNum();

  /**
   * <code>int64 view_num = 2;</code>
   * @return The viewNum.
   */
  long getViewNum();

  /**
   * <code>int32 message_type = 3;</code>
   * @return The messageType.
   */
  int getMessageType();

  /**
   * <code>int32 source = 4;</code>
   * @return The source.
   */
  int getSource();

  /**
   * <code>repeated int32 targets = 5;</code>
   * @return A list containing the targets.
   */
  java.util.List<java.lang.Integer> getTargetsList();
  /**
   * <code>repeated int32 targets = 5;</code>
   * @return The count of targets.
   */
  int getTargetsCount();
  /**
   * <code>repeated int32 targets = 5;</code>
   * @param index The index of the element to return.
   * @return The targets at the given index.
   */
  int getTargets(int index);

  /**
   * <code>repeated .RequestData requests = 6;</code>
   */
  java.util.List<com.gbft.framework.data.RequestData> 
      getRequestsList();
  /**
   * <code>repeated .RequestData requests = 6;</code>
   */
  com.gbft.framework.data.RequestData getRequests(int index);
  /**
   * <code>repeated .RequestData requests = 6;</code>
   */
  int getRequestsCount();
  /**
   * <code>repeated .RequestData requests = 6;</code>
   */
  java.util.List<? extends com.gbft.framework.data.RequestDataOrBuilder> 
      getRequestsOrBuilderList();
  /**
   * <code>repeated .RequestData requests = 6;</code>
   */
  com.gbft.framework.data.RequestDataOrBuilder getRequestsOrBuilder(
      int index);

  /**
   * <code>repeated int64 request_nums = 7;</code>
   * @return A list containing the requestNums.
   */
  java.util.List<java.lang.Long> getRequestNumsList();
  /**
   * <code>repeated int64 request_nums = 7;</code>
   * @return The count of requestNums.
   */
  int getRequestNumsCount();
  /**
   * <code>repeated int64 request_nums = 7;</code>
   * @param index The index of the element to return.
   * @return The requestNums at the given index.
   */
  long getRequestNums(int index);

  /**
   * <code>bool has_request_data = 8;</code>
   * @return The hasRequestData.
   */
  boolean getHasRequestData();

  /**
   * <code>bytes digest = 9;</code>
   * @return The digest.
   */
  com.google.protobuf.ByteString getDigest();

  /**
   * <code>repeated int32 flags = 10;</code>
   * @return A list containing the flags.
   */
  java.util.List<java.lang.Integer> getFlagsList();
  /**
   * <code>repeated int32 flags = 10;</code>
   * @return The count of flags.
   */
  int getFlagsCount();
  /**
   * <code>repeated int32 flags = 10;</code>
   * @param index The index of the element to return.
   * @return The flags at the given index.
   */
  int getFlags(int index);

  /**
   * <code>map&lt;int64, int32&gt; reply_data = 11;</code>
   */
  int getReplyDataCount();
  /**
   * <code>map&lt;int64, int32&gt; reply_data = 11;</code>
   */
  boolean containsReplyData(
      long key);
  /**
   * Use {@link #getReplyDataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Long, java.lang.Integer>
  getReplyData();
  /**
   * <code>map&lt;int64, int32&gt; reply_data = 11;</code>
   */
  java.util.Map<java.lang.Long, java.lang.Integer>
  getReplyDataMap();
  /**
   * <code>map&lt;int64, int32&gt; reply_data = 11;</code>
   */

  int getReplyDataOrDefault(
      long key,
      int defaultValue);
  /**
   * <code>map&lt;int64, int32&gt; reply_data = 11;</code>
   */

  int getReplyDataOrThrow(
      long key);

  /**
   * <code>map&lt;int32, int64&gt; extra_values = 12;</code>
   */
  int getExtraValuesCount();
  /**
   * <code>map&lt;int32, int64&gt; extra_values = 12;</code>
   */
  boolean containsExtraValues(
      int key);
  /**
   * Use {@link #getExtraValuesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, java.lang.Long>
  getExtraValues();
  /**
   * <code>map&lt;int32, int64&gt; extra_values = 12;</code>
   */
  java.util.Map<java.lang.Integer, java.lang.Long>
  getExtraValuesMap();
  /**
   * <code>map&lt;int32, int64&gt; extra_values = 12;</code>
   */

  long getExtraValuesOrDefault(
      int key,
      long defaultValue);
  /**
   * <code>map&lt;int32, int64&gt; extra_values = 12;</code>
   */

  long getExtraValuesOrThrow(
      int key);

  /**
   * <code>map&lt;int32, bytes&gt; extra_data = 13;</code>
   */
  int getExtraDataCount();
  /**
   * <code>map&lt;int32, bytes&gt; extra_data = 13;</code>
   */
  boolean containsExtraData(
      int key);
  /**
   * Use {@link #getExtraDataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, com.google.protobuf.ByteString>
  getExtraData();
  /**
   * <code>map&lt;int32, bytes&gt; extra_data = 13;</code>
   */
  java.util.Map<java.lang.Integer, com.google.protobuf.ByteString>
  getExtraDataMap();
  /**
   * <code>map&lt;int32, bytes&gt; extra_data = 13;</code>
   */

  com.google.protobuf.ByteString getExtraDataOrDefault(
      int key,
      com.google.protobuf.ByteString defaultValue);
  /**
   * <code>map&lt;int32, bytes&gt; extra_data = 13;</code>
   */

  com.google.protobuf.ByteString getExtraDataOrThrow(
      int key);

  /**
   * <code>.google.protobuf.Timestamp timestamp = 14;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 14;</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 14;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <code>.FaultData fault = 15;</code>
   * @return Whether the fault field is set.
   */
  boolean hasFault();
  /**
   * <code>.FaultData fault = 15;</code>
   * @return The fault.
   */
  com.gbft.framework.data.FaultData getFault();
  /**
   * <code>.FaultData fault = 15;</code>
   */
  com.gbft.framework.data.FaultDataOrBuilder getFaultOrBuilder();

  /**
   * <code>.FetchData fetch = 16;</code>
   * @return Whether the fetch field is set.
   */
  boolean hasFetch();
  /**
   * <code>.FetchData fetch = 16;</code>
   * @return The fetch.
   */
  com.gbft.framework.data.FetchData getFetch();
  /**
   * <code>.FetchData fetch = 16;</code>
   */
  com.gbft.framework.data.FetchDataOrBuilder getFetchOrBuilder();

  /**
   * <code>.LearningData report = 17;</code>
   * @return Whether the report field is set.
   */
  boolean hasReport();
  /**
   * <code>.LearningData report = 17;</code>
   * @return The report.
   */
  com.gbft.framework.data.LearningData getReport();
  /**
   * <code>.LearningData report = 17;</code>
   */
  com.gbft.framework.data.LearningDataOrBuilder getReportOrBuilder();

  /**
   * <code>.SwitchingData switch = 18;</code>
   * @return Whether the switch field is set.
   */
  boolean hasSwitch();
  /**
   * <code>.SwitchingData switch = 18;</code>
   * @return The switch.
   */
  com.gbft.framework.data.SwitchingData getSwitch();
  /**
   * <code>.SwitchingData switch = 18;</code>
   */
  com.gbft.framework.data.SwitchingDataOrBuilder getSwitchOrBuilder();

  /**
   * <code>repeated int64 aggregation_values = 19;</code>
   * @return A list containing the aggregationValues.
   */
  java.util.List<java.lang.Long> getAggregationValuesList();
  /**
   * <code>repeated int64 aggregation_values = 19;</code>
   * @return The count of aggregationValues.
   */
  int getAggregationValuesCount();
  /**
   * <code>repeated int64 aggregation_values = 19;</code>
   * @param index The index of the element to return.
   * @return The aggregationValues at the given index.
   */
  long getAggregationValues(int index);
}
