// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbft.proto

package com.gbft.framework.data;

public interface PluginDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PluginData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string plugin_name = 1;</code>
   * @return The pluginName.
   */
  java.lang.String getPluginName();
  /**
   * <code>string plugin_name = 1;</code>
   * @return The bytes for pluginName.
   */
  com.google.protobuf.ByteString
      getPluginNameBytes();

  /**
   * <code>int32 message_type = 2;</code>
   * @return The messageType.
   */
  int getMessageType();

  /**
   * <code>bytes data = 3;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>int32 source = 4;</code>
   * @return The source.
   */
  int getSource();

  /**
   * <code>repeated int32 targets = 5;</code>
   * @return A list containing the targets.
   */
  java.util.List<java.lang.Integer> getTargetsList();
  /**
   * <code>repeated int32 targets = 5;</code>
   * @return The count of targets.
   */
  int getTargetsCount();
  /**
   * <code>repeated int32 targets = 5;</code>
   * @param index The index of the element to return.
   * @return The targets at the given index.
   */
  int getTargets(int index);
}
