// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbft.proto

package com.gbft.framework.data;

/**
 * Protobuf type {@code PluginData}
 */
public final class PluginData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PluginData)
    PluginDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PluginData.newBuilder() to construct.
  private PluginData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PluginData() {
    pluginName_ = "";
    data_ = com.google.protobuf.ByteString.EMPTY;
    targets_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PluginData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PluginData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            pluginName_ = s;
            break;
          }
          case 16: {

            messageType_ = input.readInt32();
            break;
          }
          case 26: {

            data_ = input.readBytes();
            break;
          }
          case 32: {

            source_ = input.readInt32();
            break;
          }
          case 40: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              targets_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            targets_.addInt(input.readInt32());
            break;
          }
          case 42: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              targets_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              targets_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        targets_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gbft.framework.data.Gbft.internal_static_PluginData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gbft.framework.data.Gbft.internal_static_PluginData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gbft.framework.data.PluginData.class, com.gbft.framework.data.PluginData.Builder.class);
  }

  public static final int PLUGIN_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object pluginName_;
  /**
   * <code>string plugin_name = 1;</code>
   * @return The pluginName.
   */
  @java.lang.Override
  public java.lang.String getPluginName() {
    java.lang.Object ref = pluginName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pluginName_ = s;
      return s;
    }
  }
  /**
   * <code>string plugin_name = 1;</code>
   * @return The bytes for pluginName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPluginNameBytes() {
    java.lang.Object ref = pluginName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pluginName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_TYPE_FIELD_NUMBER = 2;
  private int messageType_;
  /**
   * <code>int32 message_type = 2;</code>
   * @return The messageType.
   */
  @java.lang.Override
  public int getMessageType() {
    return messageType_;
  }

  public static final int DATA_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString data_;
  /**
   * <code>bytes data = 3;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getData() {
    return data_;
  }

  public static final int SOURCE_FIELD_NUMBER = 4;
  private int source_;
  /**
   * <code>int32 source = 4;</code>
   * @return The source.
   */
  @java.lang.Override
  public int getSource() {
    return source_;
  }

  public static final int TARGETS_FIELD_NUMBER = 5;
  private com.google.protobuf.Internal.IntList targets_;
  /**
   * <code>repeated int32 targets = 5;</code>
   * @return A list containing the targets.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getTargetsList() {
    return targets_;
  }
  /**
   * <code>repeated int32 targets = 5;</code>
   * @return The count of targets.
   */
  public int getTargetsCount() {
    return targets_.size();
  }
  /**
   * <code>repeated int32 targets = 5;</code>
   * @param index The index of the element to return.
   * @return The targets at the given index.
   */
  public int getTargets(int index) {
    return targets_.getInt(index);
  }
  private int targetsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getPluginNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pluginName_);
    }
    if (messageType_ != 0) {
      output.writeInt32(2, messageType_);
    }
    if (!data_.isEmpty()) {
      output.writeBytes(3, data_);
    }
    if (source_ != 0) {
      output.writeInt32(4, source_);
    }
    if (getTargetsList().size() > 0) {
      output.writeUInt32NoTag(42);
      output.writeUInt32NoTag(targetsMemoizedSerializedSize);
    }
    for (int i = 0; i < targets_.size(); i++) {
      output.writeInt32NoTag(targets_.getInt(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPluginNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pluginName_);
    }
    if (messageType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, messageType_);
    }
    if (!data_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, data_);
    }
    if (source_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, source_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < targets_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(targets_.getInt(i));
      }
      size += dataSize;
      if (!getTargetsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      targetsMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gbft.framework.data.PluginData)) {
      return super.equals(obj);
    }
    com.gbft.framework.data.PluginData other = (com.gbft.framework.data.PluginData) obj;

    if (!getPluginName()
        .equals(other.getPluginName())) return false;
    if (getMessageType()
        != other.getMessageType()) return false;
    if (!getData()
        .equals(other.getData())) return false;
    if (getSource()
        != other.getSource()) return false;
    if (!getTargetsList()
        .equals(other.getTargetsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PLUGIN_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getPluginName().hashCode();
    hash = (37 * hash) + MESSAGE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMessageType();
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (37 * hash) + SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getSource();
    if (getTargetsCount() > 0) {
      hash = (37 * hash) + TARGETS_FIELD_NUMBER;
      hash = (53 * hash) + getTargetsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gbft.framework.data.PluginData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.PluginData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.PluginData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.PluginData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.PluginData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.PluginData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.PluginData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.PluginData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gbft.framework.data.PluginData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.PluginData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gbft.framework.data.PluginData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.PluginData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gbft.framework.data.PluginData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PluginData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PluginData)
      com.gbft.framework.data.PluginDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gbft.framework.data.Gbft.internal_static_PluginData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gbft.framework.data.Gbft.internal_static_PluginData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gbft.framework.data.PluginData.class, com.gbft.framework.data.PluginData.Builder.class);
    }

    // Construct using com.gbft.framework.data.PluginData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      pluginName_ = "";

      messageType_ = 0;

      data_ = com.google.protobuf.ByteString.EMPTY;

      source_ = 0;

      targets_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gbft.framework.data.Gbft.internal_static_PluginData_descriptor;
    }

    @java.lang.Override
    public com.gbft.framework.data.PluginData getDefaultInstanceForType() {
      return com.gbft.framework.data.PluginData.getDefaultInstance();
    }

    @java.lang.Override
    public com.gbft.framework.data.PluginData build() {
      com.gbft.framework.data.PluginData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gbft.framework.data.PluginData buildPartial() {
      com.gbft.framework.data.PluginData result = new com.gbft.framework.data.PluginData(this);
      int from_bitField0_ = bitField0_;
      result.pluginName_ = pluginName_;
      result.messageType_ = messageType_;
      result.data_ = data_;
      result.source_ = source_;
      if (((bitField0_ & 0x00000001) != 0)) {
        targets_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.targets_ = targets_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gbft.framework.data.PluginData) {
        return mergeFrom((com.gbft.framework.data.PluginData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gbft.framework.data.PluginData other) {
      if (other == com.gbft.framework.data.PluginData.getDefaultInstance()) return this;
      if (!other.getPluginName().isEmpty()) {
        pluginName_ = other.pluginName_;
        onChanged();
      }
      if (other.getMessageType() != 0) {
        setMessageType(other.getMessageType());
      }
      if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
        setData(other.getData());
      }
      if (other.getSource() != 0) {
        setSource(other.getSource());
      }
      if (!other.targets_.isEmpty()) {
        if (targets_.isEmpty()) {
          targets_ = other.targets_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureTargetsIsMutable();
          targets_.addAll(other.targets_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gbft.framework.data.PluginData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gbft.framework.data.PluginData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object pluginName_ = "";
    /**
     * <code>string plugin_name = 1;</code>
     * @return The pluginName.
     */
    public java.lang.String getPluginName() {
      java.lang.Object ref = pluginName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pluginName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string plugin_name = 1;</code>
     * @return The bytes for pluginName.
     */
    public com.google.protobuf.ByteString
        getPluginNameBytes() {
      java.lang.Object ref = pluginName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pluginName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string plugin_name = 1;</code>
     * @param value The pluginName to set.
     * @return This builder for chaining.
     */
    public Builder setPluginName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pluginName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string plugin_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPluginName() {
      
      pluginName_ = getDefaultInstance().getPluginName();
      onChanged();
      return this;
    }
    /**
     * <code>string plugin_name = 1;</code>
     * @param value The bytes for pluginName to set.
     * @return This builder for chaining.
     */
    public Builder setPluginNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pluginName_ = value;
      onChanged();
      return this;
    }

    private int messageType_ ;
    /**
     * <code>int32 message_type = 2;</code>
     * @return The messageType.
     */
    @java.lang.Override
    public int getMessageType() {
      return messageType_;
    }
    /**
     * <code>int32 message_type = 2;</code>
     * @param value The messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageType(int value) {
      
      messageType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 message_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageType() {
      
      messageType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes data = 3;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes data = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }

    private int source_ ;
    /**
     * <code>int32 source = 4;</code>
     * @return The source.
     */
    @java.lang.Override
    public int getSource() {
      return source_;
    }
    /**
     * <code>int32 source = 4;</code>
     * @param value The source to set.
     * @return This builder for chaining.
     */
    public Builder setSource(int value) {
      
      source_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 source = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSource() {
      
      source_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList targets_ = emptyIntList();
    private void ensureTargetsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        targets_ = mutableCopy(targets_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 targets = 5;</code>
     * @return A list containing the targets.
     */
    public java.util.List<java.lang.Integer>
        getTargetsList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(targets_) : targets_;
    }
    /**
     * <code>repeated int32 targets = 5;</code>
     * @return The count of targets.
     */
    public int getTargetsCount() {
      return targets_.size();
    }
    /**
     * <code>repeated int32 targets = 5;</code>
     * @param index The index of the element to return.
     * @return The targets at the given index.
     */
    public int getTargets(int index) {
      return targets_.getInt(index);
    }
    /**
     * <code>repeated int32 targets = 5;</code>
     * @param index The index to set the value at.
     * @param value The targets to set.
     * @return This builder for chaining.
     */
    public Builder setTargets(
        int index, int value) {
      ensureTargetsIsMutable();
      targets_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 targets = 5;</code>
     * @param value The targets to add.
     * @return This builder for chaining.
     */
    public Builder addTargets(int value) {
      ensureTargetsIsMutable();
      targets_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 targets = 5;</code>
     * @param values The targets to add.
     * @return This builder for chaining.
     */
    public Builder addAllTargets(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureTargetsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, targets_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 targets = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargets() {
      targets_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PluginData)
  }

  // @@protoc_insertion_point(class_scope:PluginData)
  private static final com.gbft.framework.data.PluginData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gbft.framework.data.PluginData();
  }

  public static com.gbft.framework.data.PluginData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PluginData>
      PARSER = new com.google.protobuf.AbstractParser<PluginData>() {
    @java.lang.Override
    public PluginData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PluginData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PluginData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PluginData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gbft.framework.data.PluginData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

