// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbft.proto

package com.gbft.framework.data;

/**
 * Protobuf type {@code ReportData}
 */
public final class ReportData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ReportData)
    ReportDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReportData.newBuilder() to construct.
  private ReportData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReportData() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReportData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReportData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              reportData_ = com.google.protobuf.MapField.newMapField(
                  ReportDataDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, com.gbft.framework.data.ReportData.ReportItem>
            reportData__ = input.readMessage(
                ReportDataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            reportData_.getMutableMap().put(
                reportData__.getKey(), reportData__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gbft.framework.data.Gbft.internal_static_ReportData_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetReportData();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gbft.framework.data.Gbft.internal_static_ReportData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gbft.framework.data.ReportData.class, com.gbft.framework.data.ReportData.Builder.class);
  }

  public interface ReportItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReportData.ReportItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, string&gt; item_data = 2;</code>
     */
    int getItemDataCount();
    /**
     * <code>map&lt;string, string&gt; item_data = 2;</code>
     */
    boolean containsItemData(
        java.lang.String key);
    /**
     * Use {@link #getItemDataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getItemData();
    /**
     * <code>map&lt;string, string&gt; item_data = 2;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getItemDataMap();
    /**
     * <code>map&lt;string, string&gt; item_data = 2;</code>
     */

    java.lang.String getItemDataOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; item_data = 2;</code>
     */

    java.lang.String getItemDataOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code ReportData.ReportItem}
   */
  public static final class ReportItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReportData.ReportItem)
      ReportItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReportItem.newBuilder() to construct.
    private ReportItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReportItem() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReportItem();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReportItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                itemData_ = com.google.protobuf.MapField.newMapField(
                    ItemDataDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              itemData__ = input.readMessage(
                  ItemDataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              itemData_.getMutableMap().put(
                  itemData__.getKey(), itemData__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gbft.framework.data.Gbft.internal_static_ReportData_ReportItem_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetItemData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gbft.framework.data.Gbft.internal_static_ReportData_ReportItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gbft.framework.data.ReportData.ReportItem.class, com.gbft.framework.data.ReportData.ReportItem.Builder.class);
    }

    public static final int ITEM_DATA_FIELD_NUMBER = 2;
    private static final class ItemDataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.gbft.framework.data.Gbft.internal_static_ReportData_ReportItem_ItemDataEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> itemData_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetItemData() {
      if (itemData_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ItemDataDefaultEntryHolder.defaultEntry);
      }
      return itemData_;
    }

    public int getItemDataCount() {
      return internalGetItemData().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; item_data = 2;</code>
     */

    @java.lang.Override
    public boolean containsItemData(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetItemData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getItemDataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getItemData() {
      return getItemDataMap();
    }
    /**
     * <code>map&lt;string, string&gt; item_data = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getItemDataMap() {
      return internalGetItemData().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; item_data = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getItemDataOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetItemData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; item_data = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getItemDataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetItemData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetItemData(),
          ItemDataDefaultEntryHolder.defaultEntry,
          2);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetItemData().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        itemData__ = ItemDataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, itemData__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gbft.framework.data.ReportData.ReportItem)) {
        return super.equals(obj);
      }
      com.gbft.framework.data.ReportData.ReportItem other = (com.gbft.framework.data.ReportData.ReportItem) obj;

      if (!internalGetItemData().equals(
          other.internalGetItemData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetItemData().getMap().isEmpty()) {
        hash = (37 * hash) + ITEM_DATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetItemData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gbft.framework.data.ReportData.ReportItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gbft.framework.data.ReportData.ReportItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gbft.framework.data.ReportData.ReportItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gbft.framework.data.ReportData.ReportItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gbft.framework.data.ReportData.ReportItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gbft.framework.data.ReportData.ReportItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gbft.framework.data.ReportData.ReportItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gbft.framework.data.ReportData.ReportItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gbft.framework.data.ReportData.ReportItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gbft.framework.data.ReportData.ReportItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gbft.framework.data.ReportData.ReportItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gbft.framework.data.ReportData.ReportItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gbft.framework.data.ReportData.ReportItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReportData.ReportItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReportData.ReportItem)
        com.gbft.framework.data.ReportData.ReportItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gbft.framework.data.Gbft.internal_static_ReportData_ReportItem_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetItemData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableItemData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gbft.framework.data.Gbft.internal_static_ReportData_ReportItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gbft.framework.data.ReportData.ReportItem.class, com.gbft.framework.data.ReportData.ReportItem.Builder.class);
      }

      // Construct using com.gbft.framework.data.ReportData.ReportItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableItemData().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gbft.framework.data.Gbft.internal_static_ReportData_ReportItem_descriptor;
      }

      @java.lang.Override
      public com.gbft.framework.data.ReportData.ReportItem getDefaultInstanceForType() {
        return com.gbft.framework.data.ReportData.ReportItem.getDefaultInstance();
      }

      @java.lang.Override
      public com.gbft.framework.data.ReportData.ReportItem build() {
        com.gbft.framework.data.ReportData.ReportItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gbft.framework.data.ReportData.ReportItem buildPartial() {
        com.gbft.framework.data.ReportData.ReportItem result = new com.gbft.framework.data.ReportData.ReportItem(this);
        int from_bitField0_ = bitField0_;
        result.itemData_ = internalGetItemData();
        result.itemData_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gbft.framework.data.ReportData.ReportItem) {
          return mergeFrom((com.gbft.framework.data.ReportData.ReportItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gbft.framework.data.ReportData.ReportItem other) {
        if (other == com.gbft.framework.data.ReportData.ReportItem.getDefaultInstance()) return this;
        internalGetMutableItemData().mergeFrom(
            other.internalGetItemData());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gbft.framework.data.ReportData.ReportItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gbft.framework.data.ReportData.ReportItem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> itemData_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetItemData() {
        if (itemData_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ItemDataDefaultEntryHolder.defaultEntry);
        }
        return itemData_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableItemData() {
        onChanged();;
        if (itemData_ == null) {
          itemData_ = com.google.protobuf.MapField.newMapField(
              ItemDataDefaultEntryHolder.defaultEntry);
        }
        if (!itemData_.isMutable()) {
          itemData_ = itemData_.copy();
        }
        return itemData_;
      }

      public int getItemDataCount() {
        return internalGetItemData().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; item_data = 2;</code>
       */

      @java.lang.Override
      public boolean containsItemData(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetItemData().getMap().containsKey(key);
      }
      /**
       * Use {@link #getItemDataMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getItemData() {
        return getItemDataMap();
      }
      /**
       * <code>map&lt;string, string&gt; item_data = 2;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getItemDataMap() {
        return internalGetItemData().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; item_data = 2;</code>
       */
      @java.lang.Override

      public java.lang.String getItemDataOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetItemData().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; item_data = 2;</code>
       */
      @java.lang.Override

      public java.lang.String getItemDataOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetItemData().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearItemData() {
        internalGetMutableItemData().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; item_data = 2;</code>
       */

      public Builder removeItemData(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableItemData().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableItemData() {
        return internalGetMutableItemData().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; item_data = 2;</code>
       */
      public Builder putItemData(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableItemData().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; item_data = 2;</code>
       */

      public Builder putAllItemData(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableItemData().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReportData.ReportItem)
    }

    // @@protoc_insertion_point(class_scope:ReportData.ReportItem)
    private static final com.gbft.framework.data.ReportData.ReportItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gbft.framework.data.ReportData.ReportItem();
    }

    public static com.gbft.framework.data.ReportData.ReportItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReportItem>
        PARSER = new com.google.protobuf.AbstractParser<ReportItem>() {
      @java.lang.Override
      public ReportItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReportItem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReportItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReportItem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gbft.framework.data.ReportData.ReportItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int REPORT_DATA_FIELD_NUMBER = 1;
  private static final class ReportDataDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.gbft.framework.data.ReportData.ReportItem> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.gbft.framework.data.ReportData.ReportItem>newDefaultInstance(
                com.gbft.framework.data.Gbft.internal_static_ReportData_ReportDataEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.gbft.framework.data.ReportData.ReportItem.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, com.gbft.framework.data.ReportData.ReportItem> reportData_;
  private com.google.protobuf.MapField<java.lang.String, com.gbft.framework.data.ReportData.ReportItem>
  internalGetReportData() {
    if (reportData_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ReportDataDefaultEntryHolder.defaultEntry);
    }
    return reportData_;
  }

  public int getReportDataCount() {
    return internalGetReportData().getMap().size();
  }
  /**
   * <code>map&lt;string, .ReportData.ReportItem&gt; report_data = 1;</code>
   */

  @java.lang.Override
  public boolean containsReportData(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetReportData().getMap().containsKey(key);
  }
  /**
   * Use {@link #getReportDataMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.gbft.framework.data.ReportData.ReportItem> getReportData() {
    return getReportDataMap();
  }
  /**
   * <code>map&lt;string, .ReportData.ReportItem&gt; report_data = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, com.gbft.framework.data.ReportData.ReportItem> getReportDataMap() {
    return internalGetReportData().getMap();
  }
  /**
   * <code>map&lt;string, .ReportData.ReportItem&gt; report_data = 1;</code>
   */
  @java.lang.Override

  public com.gbft.framework.data.ReportData.ReportItem getReportDataOrDefault(
      java.lang.String key,
      com.gbft.framework.data.ReportData.ReportItem defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.gbft.framework.data.ReportData.ReportItem> map =
        internalGetReportData().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .ReportData.ReportItem&gt; report_data = 1;</code>
   */
  @java.lang.Override

  public com.gbft.framework.data.ReportData.ReportItem getReportDataOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.gbft.framework.data.ReportData.ReportItem> map =
        internalGetReportData().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetReportData(),
        ReportDataDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, com.gbft.framework.data.ReportData.ReportItem> entry
         : internalGetReportData().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.gbft.framework.data.ReportData.ReportItem>
      reportData__ = ReportDataDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, reportData__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gbft.framework.data.ReportData)) {
      return super.equals(obj);
    }
    com.gbft.framework.data.ReportData other = (com.gbft.framework.data.ReportData) obj;

    if (!internalGetReportData().equals(
        other.internalGetReportData())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetReportData().getMap().isEmpty()) {
      hash = (37 * hash) + REPORT_DATA_FIELD_NUMBER;
      hash = (53 * hash) + internalGetReportData().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gbft.framework.data.ReportData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.ReportData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.ReportData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.ReportData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.ReportData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.ReportData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.ReportData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.ReportData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gbft.framework.data.ReportData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.ReportData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gbft.framework.data.ReportData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.ReportData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gbft.framework.data.ReportData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ReportData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ReportData)
      com.gbft.framework.data.ReportDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gbft.framework.data.Gbft.internal_static_ReportData_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetReportData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableReportData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gbft.framework.data.Gbft.internal_static_ReportData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gbft.framework.data.ReportData.class, com.gbft.framework.data.ReportData.Builder.class);
    }

    // Construct using com.gbft.framework.data.ReportData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableReportData().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gbft.framework.data.Gbft.internal_static_ReportData_descriptor;
    }

    @java.lang.Override
    public com.gbft.framework.data.ReportData getDefaultInstanceForType() {
      return com.gbft.framework.data.ReportData.getDefaultInstance();
    }

    @java.lang.Override
    public com.gbft.framework.data.ReportData build() {
      com.gbft.framework.data.ReportData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gbft.framework.data.ReportData buildPartial() {
      com.gbft.framework.data.ReportData result = new com.gbft.framework.data.ReportData(this);
      int from_bitField0_ = bitField0_;
      result.reportData_ = internalGetReportData();
      result.reportData_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gbft.framework.data.ReportData) {
        return mergeFrom((com.gbft.framework.data.ReportData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gbft.framework.data.ReportData other) {
      if (other == com.gbft.framework.data.ReportData.getDefaultInstance()) return this;
      internalGetMutableReportData().mergeFrom(
          other.internalGetReportData());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gbft.framework.data.ReportData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gbft.framework.data.ReportData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, com.gbft.framework.data.ReportData.ReportItem> reportData_;
    private com.google.protobuf.MapField<java.lang.String, com.gbft.framework.data.ReportData.ReportItem>
    internalGetReportData() {
      if (reportData_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ReportDataDefaultEntryHolder.defaultEntry);
      }
      return reportData_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.gbft.framework.data.ReportData.ReportItem>
    internalGetMutableReportData() {
      onChanged();;
      if (reportData_ == null) {
        reportData_ = com.google.protobuf.MapField.newMapField(
            ReportDataDefaultEntryHolder.defaultEntry);
      }
      if (!reportData_.isMutable()) {
        reportData_ = reportData_.copy();
      }
      return reportData_;
    }

    public int getReportDataCount() {
      return internalGetReportData().getMap().size();
    }
    /**
     * <code>map&lt;string, .ReportData.ReportItem&gt; report_data = 1;</code>
     */

    @java.lang.Override
    public boolean containsReportData(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetReportData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getReportDataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.gbft.framework.data.ReportData.ReportItem> getReportData() {
      return getReportDataMap();
    }
    /**
     * <code>map&lt;string, .ReportData.ReportItem&gt; report_data = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.gbft.framework.data.ReportData.ReportItem> getReportDataMap() {
      return internalGetReportData().getMap();
    }
    /**
     * <code>map&lt;string, .ReportData.ReportItem&gt; report_data = 1;</code>
     */
    @java.lang.Override

    public com.gbft.framework.data.ReportData.ReportItem getReportDataOrDefault(
        java.lang.String key,
        com.gbft.framework.data.ReportData.ReportItem defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.gbft.framework.data.ReportData.ReportItem> map =
          internalGetReportData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .ReportData.ReportItem&gt; report_data = 1;</code>
     */
    @java.lang.Override

    public com.gbft.framework.data.ReportData.ReportItem getReportDataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.gbft.framework.data.ReportData.ReportItem> map =
          internalGetReportData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearReportData() {
      internalGetMutableReportData().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .ReportData.ReportItem&gt; report_data = 1;</code>
     */

    public Builder removeReportData(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableReportData().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.gbft.framework.data.ReportData.ReportItem>
    getMutableReportData() {
      return internalGetMutableReportData().getMutableMap();
    }
    /**
     * <code>map&lt;string, .ReportData.ReportItem&gt; report_data = 1;</code>
     */
    public Builder putReportData(
        java.lang.String key,
        com.gbft.framework.data.ReportData.ReportItem value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableReportData().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .ReportData.ReportItem&gt; report_data = 1;</code>
     */

    public Builder putAllReportData(
        java.util.Map<java.lang.String, com.gbft.framework.data.ReportData.ReportItem> values) {
      internalGetMutableReportData().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ReportData)
  }

  // @@protoc_insertion_point(class_scope:ReportData)
  private static final com.gbft.framework.data.ReportData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gbft.framework.data.ReportData();
  }

  public static com.gbft.framework.data.ReportData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReportData>
      PARSER = new com.google.protobuf.AbstractParser<ReportData>() {
    @java.lang.Override
    public ReportData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReportData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReportData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReportData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gbft.framework.data.ReportData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

