// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbft.proto

package com.gbft.framework.data;

/**
 * Protobuf type {@code RequestData}
 */
public final class RequestData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RequestData)
    RequestDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestData.newBuilder() to construct.
  private RequestData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestData() {
    operation_ = 0;
    reportQuorum_ = java.util.Collections.emptyList();
    requestDummy_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RequestData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RequestData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            client_ = input.readInt32();
            break;
          }
          case 16: {

            requestNum_ = input.readInt64();
            break;
          }
          case 24: {

            record_ = input.readInt32();
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            operation_ = rawValue;
            break;
          }
          case 40: {

            value_ = input.readInt32();
            break;
          }
          case 50: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (timestamp_ != null) {
              subBuilder = timestamp_.toBuilder();
            }
            timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timestamp_);
              timestamp_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              reportQuorum_ = new java.util.ArrayList<com.gbft.framework.data.LearningData>();
              mutable_bitField0_ |= 0x00000001;
            }
            reportQuorum_.add(
                input.readMessage(com.gbft.framework.data.LearningData.parser(), extensionRegistry));
            break;
          }
          case 66: {

            requestDummy_ = input.readBytes();
            break;
          }
          case 72: {

            computeFactor_ = input.readInt32();
            break;
          }
          case 80: {

            replySize_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        reportQuorum_ = java.util.Collections.unmodifiableList(reportQuorum_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gbft.framework.data.Gbft.internal_static_RequestData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gbft.framework.data.Gbft.internal_static_RequestData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gbft.framework.data.RequestData.class, com.gbft.framework.data.RequestData.Builder.class);
  }

  /**
   * Protobuf enum {@code RequestData.Operation}
   */
  public enum Operation
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NOP = 0;</code>
     */
    NOP(0),
    /**
     * <code>ADD = 1;</code>
     */
    ADD(1),
    /**
     * <code>SUB = 2;</code>
     */
    SUB(2),
    /**
     * <code>INC = 3;</code>
     */
    INC(3),
    /**
     * <code>DEC = 4;</code>
     */
    DEC(4),
    /**
     * <code>READ_ONLY = 5;</code>
     */
    READ_ONLY(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NOP = 0;</code>
     */
    public static final int NOP_VALUE = 0;
    /**
     * <code>ADD = 1;</code>
     */
    public static final int ADD_VALUE = 1;
    /**
     * <code>SUB = 2;</code>
     */
    public static final int SUB_VALUE = 2;
    /**
     * <code>INC = 3;</code>
     */
    public static final int INC_VALUE = 3;
    /**
     * <code>DEC = 4;</code>
     */
    public static final int DEC_VALUE = 4;
    /**
     * <code>READ_ONLY = 5;</code>
     */
    public static final int READ_ONLY_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Operation valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Operation forNumber(int value) {
      switch (value) {
        case 0: return NOP;
        case 1: return ADD;
        case 2: return SUB;
        case 3: return INC;
        case 4: return DEC;
        case 5: return READ_ONLY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Operation>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Operation> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
            public Operation findValueByNumber(int number) {
              return Operation.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.gbft.framework.data.RequestData.getDescriptor().getEnumTypes().get(0);
    }

    private static final Operation[] VALUES = values();

    public static Operation valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Operation(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:RequestData.Operation)
  }

  public static final int CLIENT_FIELD_NUMBER = 1;
  private int client_;
  /**
   * <code>int32 client = 1;</code>
   * @return The client.
   */
  @java.lang.Override
  public int getClient() {
    return client_;
  }

  public static final int REQUEST_NUM_FIELD_NUMBER = 2;
  private long requestNum_;
  /**
   * <code>int64 request_num = 2;</code>
   * @return The requestNum.
   */
  @java.lang.Override
  public long getRequestNum() {
    return requestNum_;
  }

  public static final int RECORD_FIELD_NUMBER = 3;
  private int record_;
  /**
   * <code>int32 record = 3;</code>
   * @return The record.
   */
  @java.lang.Override
  public int getRecord() {
    return record_;
  }

  public static final int OPERATION_FIELD_NUMBER = 4;
  private int operation_;
  /**
   * <code>.RequestData.Operation operation = 4;</code>
   * @return The enum numeric value on the wire for operation.
   */
  @java.lang.Override public int getOperationValue() {
    return operation_;
  }
  /**
   * <code>.RequestData.Operation operation = 4;</code>
   * @return The operation.
   */
  @java.lang.Override public com.gbft.framework.data.RequestData.Operation getOperation() {
    @SuppressWarnings("deprecation")
    com.gbft.framework.data.RequestData.Operation result = com.gbft.framework.data.RequestData.Operation.valueOf(operation_);
    return result == null ? com.gbft.framework.data.RequestData.Operation.UNRECOGNIZED : result;
  }

  public static final int VALUE_FIELD_NUMBER = 5;
  private int value_;
  /**
   * <code>int32 value = 5;</code>
   * @return The value.
   */
  @java.lang.Override
  public int getValue() {
    return value_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <code>.google.protobuf.Timestamp timestamp = 6;</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return timestamp_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 6;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return getTimestamp();
  }

  public static final int REPORT_QUORUM_FIELD_NUMBER = 7;
  private java.util.List<com.gbft.framework.data.LearningData> reportQuorum_;
  /**
   * <code>repeated .LearningData report_quorum = 7;</code>
   */
  @java.lang.Override
  public java.util.List<com.gbft.framework.data.LearningData> getReportQuorumList() {
    return reportQuorum_;
  }
  /**
   * <code>repeated .LearningData report_quorum = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.gbft.framework.data.LearningDataOrBuilder> 
      getReportQuorumOrBuilderList() {
    return reportQuorum_;
  }
  /**
   * <code>repeated .LearningData report_quorum = 7;</code>
   */
  @java.lang.Override
  public int getReportQuorumCount() {
    return reportQuorum_.size();
  }
  /**
   * <code>repeated .LearningData report_quorum = 7;</code>
   */
  @java.lang.Override
  public com.gbft.framework.data.LearningData getReportQuorum(int index) {
    return reportQuorum_.get(index);
  }
  /**
   * <code>repeated .LearningData report_quorum = 7;</code>
   */
  @java.lang.Override
  public com.gbft.framework.data.LearningDataOrBuilder getReportQuorumOrBuilder(
      int index) {
    return reportQuorum_.get(index);
  }

  public static final int REQUEST_DUMMY_FIELD_NUMBER = 8;
  private com.google.protobuf.ByteString requestDummy_;
  /**
   * <code>bytes request_dummy = 8;</code>
   * @return The requestDummy.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getRequestDummy() {
    return requestDummy_;
  }

  public static final int COMPUTE_FACTOR_FIELD_NUMBER = 9;
  private int computeFactor_;
  /**
   * <code>int32 compute_factor = 9;</code>
   * @return The computeFactor.
   */
  @java.lang.Override
  public int getComputeFactor() {
    return computeFactor_;
  }

  public static final int REPLY_SIZE_FIELD_NUMBER = 10;
  private int replySize_;
  /**
   * <code>int32 reply_size = 10;</code>
   * @return The replySize.
   */
  @java.lang.Override
  public int getReplySize() {
    return replySize_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (client_ != 0) {
      output.writeInt32(1, client_);
    }
    if (requestNum_ != 0L) {
      output.writeInt64(2, requestNum_);
    }
    if (record_ != 0) {
      output.writeInt32(3, record_);
    }
    if (operation_ != com.gbft.framework.data.RequestData.Operation.NOP.getNumber()) {
      output.writeEnum(4, operation_);
    }
    if (value_ != 0) {
      output.writeInt32(5, value_);
    }
    if (timestamp_ != null) {
      output.writeMessage(6, getTimestamp());
    }
    for (int i = 0; i < reportQuorum_.size(); i++) {
      output.writeMessage(7, reportQuorum_.get(i));
    }
    if (!requestDummy_.isEmpty()) {
      output.writeBytes(8, requestDummy_);
    }
    if (computeFactor_ != 0) {
      output.writeInt32(9, computeFactor_);
    }
    if (replySize_ != 0) {
      output.writeInt32(10, replySize_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (client_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, client_);
    }
    if (requestNum_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, requestNum_);
    }
    if (record_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, record_);
    }
    if (operation_ != com.gbft.framework.data.RequestData.Operation.NOP.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, operation_);
    }
    if (value_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, value_);
    }
    if (timestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getTimestamp());
    }
    for (int i = 0; i < reportQuorum_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, reportQuorum_.get(i));
    }
    if (!requestDummy_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(8, requestDummy_);
    }
    if (computeFactor_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, computeFactor_);
    }
    if (replySize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, replySize_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gbft.framework.data.RequestData)) {
      return super.equals(obj);
    }
    com.gbft.framework.data.RequestData other = (com.gbft.framework.data.RequestData) obj;

    if (getClient()
        != other.getClient()) return false;
    if (getRequestNum()
        != other.getRequestNum()) return false;
    if (getRecord()
        != other.getRecord()) return false;
    if (operation_ != other.operation_) return false;
    if (getValue()
        != other.getValue()) return false;
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
    }
    if (!getReportQuorumList()
        .equals(other.getReportQuorumList())) return false;
    if (!getRequestDummy()
        .equals(other.getRequestDummy())) return false;
    if (getComputeFactor()
        != other.getComputeFactor()) return false;
    if (getReplySize()
        != other.getReplySize()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENT_FIELD_NUMBER;
    hash = (53 * hash) + getClient();
    hash = (37 * hash) + REQUEST_NUM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRequestNum());
    hash = (37 * hash) + RECORD_FIELD_NUMBER;
    hash = (53 * hash) + getRecord();
    hash = (37 * hash) + OPERATION_FIELD_NUMBER;
    hash = (53 * hash) + operation_;
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue();
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    if (getReportQuorumCount() > 0) {
      hash = (37 * hash) + REPORT_QUORUM_FIELD_NUMBER;
      hash = (53 * hash) + getReportQuorumList().hashCode();
    }
    hash = (37 * hash) + REQUEST_DUMMY_FIELD_NUMBER;
    hash = (53 * hash) + getRequestDummy().hashCode();
    hash = (37 * hash) + COMPUTE_FACTOR_FIELD_NUMBER;
    hash = (53 * hash) + getComputeFactor();
    hash = (37 * hash) + REPLY_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getReplySize();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gbft.framework.data.RequestData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.RequestData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.RequestData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.RequestData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.RequestData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.RequestData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.RequestData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.RequestData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gbft.framework.data.RequestData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.RequestData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gbft.framework.data.RequestData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.RequestData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gbft.framework.data.RequestData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RequestData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RequestData)
      com.gbft.framework.data.RequestDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gbft.framework.data.Gbft.internal_static_RequestData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gbft.framework.data.Gbft.internal_static_RequestData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gbft.framework.data.RequestData.class, com.gbft.framework.data.RequestData.Builder.class);
    }

    // Construct using com.gbft.framework.data.RequestData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getReportQuorumFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      client_ = 0;

      requestNum_ = 0L;

      record_ = 0;

      operation_ = 0;

      value_ = 0;

      if (timestampBuilder_ == null) {
        timestamp_ = null;
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }
      if (reportQuorumBuilder_ == null) {
        reportQuorum_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        reportQuorumBuilder_.clear();
      }
      requestDummy_ = com.google.protobuf.ByteString.EMPTY;

      computeFactor_ = 0;

      replySize_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gbft.framework.data.Gbft.internal_static_RequestData_descriptor;
    }

    @java.lang.Override
    public com.gbft.framework.data.RequestData getDefaultInstanceForType() {
      return com.gbft.framework.data.RequestData.getDefaultInstance();
    }

    @java.lang.Override
    public com.gbft.framework.data.RequestData build() {
      com.gbft.framework.data.RequestData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gbft.framework.data.RequestData buildPartial() {
      com.gbft.framework.data.RequestData result = new com.gbft.framework.data.RequestData(this);
      int from_bitField0_ = bitField0_;
      result.client_ = client_;
      result.requestNum_ = requestNum_;
      result.record_ = record_;
      result.operation_ = operation_;
      result.value_ = value_;
      if (timestampBuilder_ == null) {
        result.timestamp_ = timestamp_;
      } else {
        result.timestamp_ = timestampBuilder_.build();
      }
      if (reportQuorumBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          reportQuorum_ = java.util.Collections.unmodifiableList(reportQuorum_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.reportQuorum_ = reportQuorum_;
      } else {
        result.reportQuorum_ = reportQuorumBuilder_.build();
      }
      result.requestDummy_ = requestDummy_;
      result.computeFactor_ = computeFactor_;
      result.replySize_ = replySize_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gbft.framework.data.RequestData) {
        return mergeFrom((com.gbft.framework.data.RequestData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gbft.framework.data.RequestData other) {
      if (other == com.gbft.framework.data.RequestData.getDefaultInstance()) return this;
      if (other.getClient() != 0) {
        setClient(other.getClient());
      }
      if (other.getRequestNum() != 0L) {
        setRequestNum(other.getRequestNum());
      }
      if (other.getRecord() != 0) {
        setRecord(other.getRecord());
      }
      if (other.operation_ != 0) {
        setOperationValue(other.getOperationValue());
      }
      if (other.getValue() != 0) {
        setValue(other.getValue());
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      if (reportQuorumBuilder_ == null) {
        if (!other.reportQuorum_.isEmpty()) {
          if (reportQuorum_.isEmpty()) {
            reportQuorum_ = other.reportQuorum_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureReportQuorumIsMutable();
            reportQuorum_.addAll(other.reportQuorum_);
          }
          onChanged();
        }
      } else {
        if (!other.reportQuorum_.isEmpty()) {
          if (reportQuorumBuilder_.isEmpty()) {
            reportQuorumBuilder_.dispose();
            reportQuorumBuilder_ = null;
            reportQuorum_ = other.reportQuorum_;
            bitField0_ = (bitField0_ & ~0x00000001);
            reportQuorumBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getReportQuorumFieldBuilder() : null;
          } else {
            reportQuorumBuilder_.addAllMessages(other.reportQuorum_);
          }
        }
      }
      if (other.getRequestDummy() != com.google.protobuf.ByteString.EMPTY) {
        setRequestDummy(other.getRequestDummy());
      }
      if (other.getComputeFactor() != 0) {
        setComputeFactor(other.getComputeFactor());
      }
      if (other.getReplySize() != 0) {
        setReplySize(other.getReplySize());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gbft.framework.data.RequestData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gbft.framework.data.RequestData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int client_ ;
    /**
     * <code>int32 client = 1;</code>
     * @return The client.
     */
    @java.lang.Override
    public int getClient() {
      return client_;
    }
    /**
     * <code>int32 client = 1;</code>
     * @param value The client to set.
     * @return This builder for chaining.
     */
    public Builder setClient(int value) {
      
      client_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 client = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearClient() {
      
      client_ = 0;
      onChanged();
      return this;
    }

    private long requestNum_ ;
    /**
     * <code>int64 request_num = 2;</code>
     * @return The requestNum.
     */
    @java.lang.Override
    public long getRequestNum() {
      return requestNum_;
    }
    /**
     * <code>int64 request_num = 2;</code>
     * @param value The requestNum to set.
     * @return This builder for chaining.
     */
    public Builder setRequestNum(long value) {
      
      requestNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 request_num = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestNum() {
      
      requestNum_ = 0L;
      onChanged();
      return this;
    }

    private int record_ ;
    /**
     * <code>int32 record = 3;</code>
     * @return The record.
     */
    @java.lang.Override
    public int getRecord() {
      return record_;
    }
    /**
     * <code>int32 record = 3;</code>
     * @param value The record to set.
     * @return This builder for chaining.
     */
    public Builder setRecord(int value) {
      
      record_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 record = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecord() {
      
      record_ = 0;
      onChanged();
      return this;
    }

    private int operation_ = 0;
    /**
     * <code>.RequestData.Operation operation = 4;</code>
     * @return The enum numeric value on the wire for operation.
     */
    @java.lang.Override public int getOperationValue() {
      return operation_;
    }
    /**
     * <code>.RequestData.Operation operation = 4;</code>
     * @param value The enum numeric value on the wire for operation to set.
     * @return This builder for chaining.
     */
    public Builder setOperationValue(int value) {
      
      operation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.RequestData.Operation operation = 4;</code>
     * @return The operation.
     */
    @java.lang.Override
    public com.gbft.framework.data.RequestData.Operation getOperation() {
      @SuppressWarnings("deprecation")
      com.gbft.framework.data.RequestData.Operation result = com.gbft.framework.data.RequestData.Operation.valueOf(operation_);
      return result == null ? com.gbft.framework.data.RequestData.Operation.UNRECOGNIZED : result;
    }
    /**
     * <code>.RequestData.Operation operation = 4;</code>
     * @param value The operation to set.
     * @return This builder for chaining.
     */
    public Builder setOperation(com.gbft.framework.data.RequestData.Operation value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      operation_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.RequestData.Operation operation = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperation() {
      
      operation_ = 0;
      onChanged();
      return this;
    }

    private int value_ ;
    /**
     * <code>int32 value = 5;</code>
     * @return The value.
     */
    @java.lang.Override
    public int getValue() {
      return value_;
    }
    /**
     * <code>int32 value = 5;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(int value) {
      
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 value = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      
      value_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp timestamp_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return timestampBuilder_ != null || timestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     * @return The timestamp.
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
        onChanged();
      } else {
        timestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
        onChanged();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (timestamp_ != null) {
          timestamp_ =
            com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
        } else {
          timestamp_ = value;
        }
        onChanged();
      } else {
        timestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    public Builder clearTimestamp() {
      if (timestampBuilder_ == null) {
        timestamp_ = null;
        onChanged();
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private java.util.List<com.gbft.framework.data.LearningData> reportQuorum_ =
      java.util.Collections.emptyList();
    private void ensureReportQuorumIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        reportQuorum_ = new java.util.ArrayList<com.gbft.framework.data.LearningData>(reportQuorum_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.gbft.framework.data.LearningData, com.gbft.framework.data.LearningData.Builder, com.gbft.framework.data.LearningDataOrBuilder> reportQuorumBuilder_;

    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public java.util.List<com.gbft.framework.data.LearningData> getReportQuorumList() {
      if (reportQuorumBuilder_ == null) {
        return java.util.Collections.unmodifiableList(reportQuorum_);
      } else {
        return reportQuorumBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public int getReportQuorumCount() {
      if (reportQuorumBuilder_ == null) {
        return reportQuorum_.size();
      } else {
        return reportQuorumBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public com.gbft.framework.data.LearningData getReportQuorum(int index) {
      if (reportQuorumBuilder_ == null) {
        return reportQuorum_.get(index);
      } else {
        return reportQuorumBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public Builder setReportQuorum(
        int index, com.gbft.framework.data.LearningData value) {
      if (reportQuorumBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReportQuorumIsMutable();
        reportQuorum_.set(index, value);
        onChanged();
      } else {
        reportQuorumBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public Builder setReportQuorum(
        int index, com.gbft.framework.data.LearningData.Builder builderForValue) {
      if (reportQuorumBuilder_ == null) {
        ensureReportQuorumIsMutable();
        reportQuorum_.set(index, builderForValue.build());
        onChanged();
      } else {
        reportQuorumBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public Builder addReportQuorum(com.gbft.framework.data.LearningData value) {
      if (reportQuorumBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReportQuorumIsMutable();
        reportQuorum_.add(value);
        onChanged();
      } else {
        reportQuorumBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public Builder addReportQuorum(
        int index, com.gbft.framework.data.LearningData value) {
      if (reportQuorumBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReportQuorumIsMutable();
        reportQuorum_.add(index, value);
        onChanged();
      } else {
        reportQuorumBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public Builder addReportQuorum(
        com.gbft.framework.data.LearningData.Builder builderForValue) {
      if (reportQuorumBuilder_ == null) {
        ensureReportQuorumIsMutable();
        reportQuorum_.add(builderForValue.build());
        onChanged();
      } else {
        reportQuorumBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public Builder addReportQuorum(
        int index, com.gbft.framework.data.LearningData.Builder builderForValue) {
      if (reportQuorumBuilder_ == null) {
        ensureReportQuorumIsMutable();
        reportQuorum_.add(index, builderForValue.build());
        onChanged();
      } else {
        reportQuorumBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public Builder addAllReportQuorum(
        java.lang.Iterable<? extends com.gbft.framework.data.LearningData> values) {
      if (reportQuorumBuilder_ == null) {
        ensureReportQuorumIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, reportQuorum_);
        onChanged();
      } else {
        reportQuorumBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public Builder clearReportQuorum() {
      if (reportQuorumBuilder_ == null) {
        reportQuorum_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        reportQuorumBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public Builder removeReportQuorum(int index) {
      if (reportQuorumBuilder_ == null) {
        ensureReportQuorumIsMutable();
        reportQuorum_.remove(index);
        onChanged();
      } else {
        reportQuorumBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public com.gbft.framework.data.LearningData.Builder getReportQuorumBuilder(
        int index) {
      return getReportQuorumFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public com.gbft.framework.data.LearningDataOrBuilder getReportQuorumOrBuilder(
        int index) {
      if (reportQuorumBuilder_ == null) {
        return reportQuorum_.get(index);  } else {
        return reportQuorumBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public java.util.List<? extends com.gbft.framework.data.LearningDataOrBuilder> 
         getReportQuorumOrBuilderList() {
      if (reportQuorumBuilder_ != null) {
        return reportQuorumBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(reportQuorum_);
      }
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public com.gbft.framework.data.LearningData.Builder addReportQuorumBuilder() {
      return getReportQuorumFieldBuilder().addBuilder(
          com.gbft.framework.data.LearningData.getDefaultInstance());
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public com.gbft.framework.data.LearningData.Builder addReportQuorumBuilder(
        int index) {
      return getReportQuorumFieldBuilder().addBuilder(
          index, com.gbft.framework.data.LearningData.getDefaultInstance());
    }
    /**
     * <code>repeated .LearningData report_quorum = 7;</code>
     */
    public java.util.List<com.gbft.framework.data.LearningData.Builder> 
         getReportQuorumBuilderList() {
      return getReportQuorumFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.gbft.framework.data.LearningData, com.gbft.framework.data.LearningData.Builder, com.gbft.framework.data.LearningDataOrBuilder> 
        getReportQuorumFieldBuilder() {
      if (reportQuorumBuilder_ == null) {
        reportQuorumBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.gbft.framework.data.LearningData, com.gbft.framework.data.LearningData.Builder, com.gbft.framework.data.LearningDataOrBuilder>(
                reportQuorum_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        reportQuorum_ = null;
      }
      return reportQuorumBuilder_;
    }

    private com.google.protobuf.ByteString requestDummy_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes request_dummy = 8;</code>
     * @return The requestDummy.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRequestDummy() {
      return requestDummy_;
    }
    /**
     * <code>bytes request_dummy = 8;</code>
     * @param value The requestDummy to set.
     * @return This builder for chaining.
     */
    public Builder setRequestDummy(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestDummy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes request_dummy = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestDummy() {
      
      requestDummy_ = getDefaultInstance().getRequestDummy();
      onChanged();
      return this;
    }

    private int computeFactor_ ;
    /**
     * <code>int32 compute_factor = 9;</code>
     * @return The computeFactor.
     */
    @java.lang.Override
    public int getComputeFactor() {
      return computeFactor_;
    }
    /**
     * <code>int32 compute_factor = 9;</code>
     * @param value The computeFactor to set.
     * @return This builder for chaining.
     */
    public Builder setComputeFactor(int value) {
      
      computeFactor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 compute_factor = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearComputeFactor() {
      
      computeFactor_ = 0;
      onChanged();
      return this;
    }

    private int replySize_ ;
    /**
     * <code>int32 reply_size = 10;</code>
     * @return The replySize.
     */
    @java.lang.Override
    public int getReplySize() {
      return replySize_;
    }
    /**
     * <code>int32 reply_size = 10;</code>
     * @param value The replySize to set.
     * @return This builder for chaining.
     */
    public Builder setReplySize(int value) {
      
      replySize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 reply_size = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearReplySize() {
      
      replySize_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RequestData)
  }

  // @@protoc_insertion_point(class_scope:RequestData)
  private static final com.gbft.framework.data.RequestData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gbft.framework.data.RequestData();
  }

  public static com.gbft.framework.data.RequestData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestData>
      PARSER = new com.google.protobuf.AbstractParser<RequestData>() {
    @java.lang.Override
    public RequestData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gbft.framework.data.RequestData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

