// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbft.proto

package com.gbft.framework.data;

public interface UnitDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UnitData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 unit = 1;</code>
   * @return The unit.
   */
  int getUnit();

  /**
   * <code>int32 node_count = 2;</code>
   * @return The nodeCount.
   */
  int getNodeCount();

  /**
   * <code>int32 client_count = 3;</code>
   * @return The clientCount.
   */
  int getClientCount();
}
